Repository operaton/operaton, pull requests merged in 2024-12, with the labels that each got.

#304 fix(build): Consolidate usage of maven-source-plugin
  engine-cdi/core/pom.xml
  engine-cdi/jakarta/pom.xml
  engine-rest/engine-rest-jakarta/pom.xml
  engine-rest/engine-rest/pom.xml
  engine-spring/core-6/pom.xml
  engine/pom.xml
  juel/pom.xml
  parent/pom.xml
  pom.xml
Labels: build

#306 chore(engine-dmn): Fix instanceof check and cast with pattern matching…
  engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/transform/DefaultDmnTransform.java
  engine-dmn/feel-juel/src/main/java/org/operaton/bpm/dmn/feel/impl/juel/FeelEngineImpl.java
  engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/ScalaFeelEngine.java
Labels: refactoring

#308 refactor(engine-rest): ensure proper exception code assignment in ExceptionHandlerHelper (#4600)
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/exception/ExceptionHandlerHelper.java
Labels: backport-c7

#281 Make distros downloadable as separate artifacts
  .github/scripts/prepare-distros-archive.sh
  .github/workflows/build.yml
  .github/workflows/nighly-build.yml
  distro/wildfly/subsystem/pom.xml
  distro/wildfly26/subsystem/pom.xml
  parent/pom.xml
  pom.xml
Labels: build

#312 chore(build): Finalize release build for 1.0.0-beta-2
  .github/jreleaser/changelog.tpl
  .github/scripts/set-project-version.sh
  .github/workflows/release.yml
  .gitignore
  distro/tomcat/assembly/pom.xml
  distro/webjar/pom.xml
  distro/webjar/src/main/java/org/operaton/bpm/webapp/Dummy.java
  engine-rest/engine-rest-openapi/pom.xml
  engine/pom.xml
  jreleaser.yml
  parent/pom.xml
  pom.xml
  quarkus-extension/engine/qa/pom.xml
  spring-boot-starter/starter-qa/pom.xml
Labels: build

#305 chore(engine): Fix instanceof check and cast with pattern matching in engine
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ServiceTaskDelegateExpressionActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/helper/BpmnExceptionHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/listener/ClassDelegateExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/listener/DelegateExpressionExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/behavior/StageActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/behavior/TaskActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/entity/runtime/CaseExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/execution/CmmnExecution.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/listener/ClassDelegateCaseExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/listener/DelegateExpressionCaseExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/operation/AbstractAtomicOperationCaseExecutionComplete.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/operation/AbstractAtomicOperationCaseExecutionSuspend.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/operation/AbstractAtomicOperationCaseExecutionTerminate.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/operation/AtomicOperationCaseExecutionDisable.java
  engine/src/main/java/org/operaton/bpm/engine/impl/context/Context.java
  engine/src/main/java/org/operaton/bpm/engine/impl/context/ProcessApplicationContextUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/BaseCallableElement.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/operation/AbstractEventAtomicOperation.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/variable/scope/VariableListenerInvocationListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/AbstractPersistenceSession.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/EnginePersistenceLogger.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/cache/CachedDbEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/operation/DbOperationManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/operaton/bpm/engine/impl/delegate/DefaultDelegateInterceptor.java
  engine/src/main/java/org/operaton/bpm/engine/impl/digest/_apacheCommonsCodec/Base64.java
  engine/src/main/java/org/operaton/bpm/engine/impl/event/ConditionalEventHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/handler/DefaultFormFieldValidatorContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/handler/DefaultFormHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/handler/FormPropertyHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/type/DateFormType.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/handler/DbHistoryEventHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/parser/HistoryDecisionEvaluationListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/producer/DefaultHistoryEventProducer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/CommandInvocationContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobDeclaration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/NotifyAcquisitionRejectedJobsHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerDeclarationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/instance/parser/ActivityInstanceHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/instance/parser/ActivityInstanceJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/validation/instance/VariableConflictActivityInstanceValidator.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/PropertyChange.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/util/TypedValueField.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/LegacyBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationActivityEnd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationActivityInitStackNotifyListenerStart.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationActivityLeave.java
  engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/JuelScriptEngine.java
Labels: refactoring

#321 chore: Code cleanup, resolve Sonar issues
  clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/AbstractTypedValueMapper.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/VariableValue.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/mapper/ByteArrayValueMapper.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/util/GetBpmnModelElementTypeRule.java
  model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn/util/GetCmmnModelElementTypeRule.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/instance/ModelElementInstanceTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/beans/ExampleSignallableActivityBehaviorBean.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/JavaDelegateResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/JobExecutorRequestContextLocalInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/event/beans/ExecutionListenerProcessApplication.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/message/IntermediateMessageCatchEventTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/AsyncIntermediateThrowSignalEventTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/FailingJobBoundaryTimerWithDelegateVariablesTest.java
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
  spring-boot-starter/starter-qa/integration-test-webapp/invoice-example/src/main/java/org/operaton/bpm/qa/Application.java
  spring-boot-starter/starter-security/src/main/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2IdentityProvider.java
  test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/bpmn/AbstractAssertions.java
  test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/bpmn/BpmnAwareTests.java
  test-utils/assert/core/src/main/java/org/operaton/bpm/engine/test/assertions/cmmn/AbstractCaseAssert.java
Labels: refactoring

#334 chore: Resolve deprecation `Context#getExecutionContext`
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/AbstractCdiEventListener.java
  engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/scope/ProcessScope.java
  engine/src/main/java/org/operaton/bpm/engine/impl/context/Context.java
Labels: refactoring

#337 chore(testing): Remove `public` modifier from JUnit 5 test classes and test methods
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/BusinessProcessContextTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/ConfigurableProcessEngineTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/EmbeddedProcessEngineTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/ManagedJobExecutorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineConfigurationConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineDefaultConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineJobExecutorConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineProgrammaticAndConfigFileTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/deployment/ProcessEngineMultipleDeploymentTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/deployment/ProcessEngineSingleDeploymentTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/id/DefaultIdGeneratorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/lookup/ProgrammaticBeanLookupTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/TransactionIntegrationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/UserTransactionIntegrationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/conf/ChooseDatasourceConfigurationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/conf/ChooseNotExistingDatasourceConfigurationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/conf/DatasourceConfigurationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/conf/NoDefaultDatasourceConfigurationTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionClassDeploymentTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionJunit5Test.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionParentClassDeploymentTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionParentClassResourceDeploymentTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredDatabaseTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredHistoryLevelAuditTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionSetTimeTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/EnsureDbCleanTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionDeploymentIdAccess.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionDeploymentIdTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionManageDeploymentsTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionResourcesDeploymentTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/registerExtension/RegisterNewProcessEngineTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/registerExtension/RegisterProcessEngineExtensionTest.java
Labels: refactoring

#332 fix(build): Enable `run` in `distros` profile & build nightly
  .github/workflows/nighly-build.yml
  pom.xml
Labels: build

#340 Chore/set project encoding
  pom.xml
Labels: build

#343 refactor(build): Introduce `install.skip` property
  distro/run/qa/integration-tests/pom.xml
  distro/run/qa/runtime/pom.xml
  pom.xml
  qa/integration-tests-engine-jakarta/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
  qa/large-data-tests/pom.xml
  quarkus-extension/engine/qa/pom.xml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/pom.xml
  spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
  test-utils/assert/qa/pom.xml
Labels: build

#353 chore(build): Ignore alpha/beta/4.0.0 versions in plugin-updates report
  pom.xml
Labels: build

#350 Cleanup: Use StandardCharsets
  clients/java/client/src/it/java/org/operaton/bpm/client/rule/EngineRule.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/FileSerializationIT.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java
  commons/typed-values/src/test/java/org/operaton/bpm/engine/test/variables/FileValueTypeImplTest.java
  commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/AbstractHttpConnector.java
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/TypedValueAssert.java
  engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/impl/AbstractVariablesResource.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/repository/impl/CaseDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/repository/impl/DecisionDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/repository/impl/DecisionRequirementsDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/repository/impl/ProcessDefinitionResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/util/EncodingUtil.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/AbstractRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CaseExecutionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CaseInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ExecutionRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessEngineRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableLocalRestResourceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableRestResourceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/VariableInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDetailRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricVariableInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/standalone/AbstractEmptyBodyFilterTest.java
  engine/src/main/java/org/operaton/bpm/container/impl/ContainerIntegrationLogger.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/digest/Base64EncodedHashDigest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/digest/_apacheCommonsCodec/StringUtils.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/engine/JuelFormEngine.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/IoUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/ResourceUtil.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/deployment/BpmPlatformXmlLocationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/variables/FileValueProcessSerializationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/variables/FileValueSerializerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/TypedValueAssert.java
  model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/util/IoUtil.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/DemoDelegate.java
  spin/core/src/main/java/org/operaton/spin/impl/util/SpinIoUtil.java
  spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/DomXmlDataFormatWriter.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/impl/xml/dom/format/DomXmlDataFormatWriterTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/filter/redirect/ResourceLoadingProcessEnginesAppPathRootTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/filter/util/HttpClientRule.java
Labels: refactoring

#349 chore(build): Use JReleaser for nightly releases
  .github/jreleaser/changelog.tpl
  .github/scripts/jacoco-create-flag-files.sh
  .github/scripts/prepare-reports.sh
  .github/workflows/build.yml
  .github/workflows/nighly-build.yml
  .github/workflows/release.yml
  jreleaser.yml
Labels: build

#357 refactor: Use correct order for assertions
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceInteractionTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/ProcessStartingBeanPostProcessorTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/components/scope/ScopingTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/plugin/SpringProcessEnginePluginTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSFSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSLSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSingletonBeanInvocationTest.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredHistoryLevelAuditTest.java
Labels: refactoring

#361 chore: resolve deprecation org.junit.Assert.assertThat
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/configuration/JavaBasedProcessEngineConfigTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/transaction/SpringTransactionIntegrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageEventSubprocessTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestDeploymentTenantId.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentResumePreviousOnDeploymentName.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentResumePreviousOnProcessDefinitionKey.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/InvocationContextTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/dmn/DmnHistoryTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/SLSBExceptionInDelegateTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/ProcessInstanceModificationTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/TimerChangeJobDefinitionTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/TimerChangeProcessDefinitionTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/DeleteHistoricDecisionsBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/DeleteHistoricProcessInstancesBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/DeleteProcessInstancesBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/MigrationBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/ModificationBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/RestartProcessInstanceBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/SetExternalTaskRetriesBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/SetJobRetriesBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/gson/batch/UpdateProcessInstanceSuspendStateBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/removaltime/RemovalTimeBatchTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/AbstractTimestampMigrationTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/DeploymentDeployTimeTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/EventSubscriptionCreateTimeTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/ExternalTaskLockExpTimeTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/HistoricJobLogTimestampsTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/IncidentTimestampTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/JobTimestampsTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/MeterLogTimestampTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/TaskCreateTimeTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7110/timestamp/UserLockExpTimeTest.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7120/useroperationlog/annotation/SetAnnotationAuthorizationTest.java
  qa/test-db-rolling-update/test-old-engine/src/test/java/org/operaton/bpm/qa/rolling/update/timestamp/AbstractTimestampUpdateTest.java
  qa/test-db-rolling-update/test-old-engine/src/test/java/org/operaton/bpm/qa/rolling/update/timestamp/IncidentTimestampUpdateTest.java
  qa/test-db-rolling-update/test-old-engine/src/test/java/org/operaton/bpm/qa/rolling/update/timestamp/JobTimestampsUpdateTest.java
  qa/test-db-rolling-update/test-old-engine/src/test/java/org/operaton/bpm/qa/rolling/update/variable/EmptyStringVariableTest.java
Labels: refactoring

#365 feat(core): add update and delete comment Java/Rest APIs (#4565)
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/{commentId}/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/delete.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/put.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/task/{id}/comment/{commentId}/delete.ftl
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/runtime/ProcessInstanceCommentResource.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/runtime/impl/ProcessInstanceCommentResourceImpl.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/task/TaskCommentResource.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/task/impl/TaskCommentResourceImpl.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/helper/MockProvider.java
  engine/src/main/java/org/operaton/bpm/engine/EntityTypes.java
  engine/src/main/java/org/operaton/bpm/engine/TaskService.java
  engine/src/main/java/org/operaton/bpm/engine/history/UserOperationLogEntry.java
  engine/src/main/java/org/operaton/bpm/engine/impl/TaskServiceImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/auth/AuthorizationCommandChecker.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/multitenancy/TenantCommandChecker.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AddCommentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteProcessInstanceCommentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteTaskCommentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/UpdateCommentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/CommentEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/CommentManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.db2.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.h2.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mariadb.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mssql.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.mysql.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.oracle.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/create/activiti.postgres.create.history.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/db2_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/h2_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mariadb_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mssql_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/mysql_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/oracle_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/db/upgrade/postgres_engine_7.22_to_7.23.sql
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Comment.xml
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessInstanceCommentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/TaskCommentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/encoding/ProcessEngineCharacterEncodingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskLastUpdatedTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
Labels: backport-c7

#366 chore(openapi): fix process instance comment tag
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-instance/{id}/comment/get.ftl
Labels: backport-c7

#373 fix(tests): Fix OptimizeApiPageSizeTest
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/optimize/OptimizeApiPageSizeTest.java
Labels: bug, qa

#368 chore(engine,parent): Bump GraalVM to 21.3.12
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/OperatonScriptEngineManager.java
  parent/pom.xml
Labels: enhancement, dependencies, backport-c7

#370 feat(engine): include error message of unhandled BPMN error in log
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/BpmnBehaviorLogger.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/helper/BpmnExceptionHandler.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/behavior/BpmnBehaviorLoggerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerErrorThrowTest.java
  engine/src/test/resources/org/operaton/bpm/engine/test/bpmn/behavior/BpmnBehaviorLoggerTest.UnhandledBpmnError.bpmn20.xml
Labels: enhancement, backport-c7

#380 chore: Collapse consecutive assertThat statements to one
  commons/typed-values/src/test/java/org/operaton/bpm/engine/test/variables/FileValueTypeImplTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceQueryTest.java
  model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/ReadWriteTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/ModelTest.java
  spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/property/OperatonBpmPropertiesTest.java
Labels: refactoring

#379 Resolve deprecations: MockitoAnnotations & AbstractDateAssert
  engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskConditionsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CorrelateAllMessageBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ModificationExecutionAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/VariableInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTransitionInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskLastUpdatedTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/logging/TestMdcFacade.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7190/job/SetJobRetriesWithDueDateTest.java
  spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/ProcessApplicationIT.java
Labels: refactoring

#382 chore: Remove unused private members
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java
  distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/JsonPathUtil.java
  engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/registry/ActivitiStateHandlerRegistry.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceReportImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/SchemaOperationsProcessEngineBuild.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteJobsCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetNextIdBlockCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobDeclaration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/deploy/cache/CacheDeployer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/JuelScriptEngine.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramRetrievalTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/RetryCmdDeployment.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/UserTaskTestCreateTaskListener.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
  model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/ExampleCompatibilityTest.java
  model-api/dmn-model/src/test/java/org/operaton/bpm/model/dmn/OperatonExtensionsTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/JobExecutorRequestContextTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/delegation/DelegatedVariableMappingTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/mapping/Order.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/ProcessEngineExtensionDeploymentIdAccess.java
Labels: refactoring

#377 fix(tests): Fix SqlScriptTest
  database/pom.xml
  distro/sql-script/pom.xml
  distro/sql-script/src/test/java/org/operaton/bpm/sql/test/SqlScriptTest.java
Labels: bug, qa
