Repository operaton/operaton, pull requests merged in 2024-11, with the labels that each got.

#202 chore(internal-dependencies): Bump to commons-io:2.17.0
  internal-dependencies/pom.xml
Labels: dependencies

#206 feat(ci): Improve build performance by configure surefire forkCount (#205)
  engine-plugins/identity-ldap/pom.xml
  engine-rest/pom.xml
  engine/pom.xml
  parent/pom.xml
  spring-boot-starter/pom.xml
  webapps/pom.xml
Labels: build

#228 refactor(tests): JUnit5 migration - spring-boot-starter
  pom.xml
  spring-boot-starter/starter-qa/integration-test-liquibase/pom.xml
  spring-boot-starter/starter-qa/integration-test-liquibase/src/test/java/org/operaton/bpm/springboot/project/qa/liquibase/LiquibaseApplicationIT.java
  spring-boot-starter/starter-qa/integration-test-plugins/pom.xml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/src/test/java/org/operaton/bpm/springboot/project/qa/spin/SpinApplicationTestIT.java
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/pom.xml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/src/test/java/org/operaton/bpm/springboot/project/qa/spin/SpinApplicationTestIT.java
  spring-boot-starter/starter-qa/integration-test-request-scope/pom.xml
  spring-boot-starter/starter-qa/integration-test-request-scope/src/test/java/org/operaton/bpm/springboot/project/qa/simple/RequestScopeIT.java
  spring-boot-starter/starter-qa/integration-test-simple/pom.xml
  spring-boot-starter/starter-qa/integration-test-simple/src/test/java/org/operaton/bpm/springboot/project/qa/simple/SimpleApplicationIT.java
  spring-boot-starter/starter-qa/pom.xml
Labels: enhancement

#233 chore(dmn): bump feel scala version to 1.18.1
  pom.xml
Labels: dependencies

#244 feat(ci): Define paths-ignore for files that should not trigger a build
  .github/workflows/build.yml
Labels: build

#240 chore(docs): Update TESTING.md for JUnit 5
  TESTING.md
Labels: documentation

#243 fix(build,juel): Use managed version of jakarta-el and use compile scope for juel
  juel/pom.xml
Labels: build

#257 test(spin): exclude time zone from unit tests as it is hard coded
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/XmlTestUtil.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomMapJavaToXmlScriptTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomMapJavaToXmlTest.java
Labels: qa, backport

#253 fix(install): skip operaton-qa-integration-tests-webapps-shared-engine for install goal (#226)
  qa/integration-tests-webapps/shared-engine/pom.xml
Labels: build

#259 Disable failsafe in external task client
  clients/java/client/pom.xml
Labels: build, qa

#256 feat(engine): don't fail on change variables async when process instance does not exist
  engine/src/main/java/org/operaton/bpm/engine/impl/batch/variables/BatchSetVariablesHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractVariableCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetExecutionVariablesCmd.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/JobEntityAndJobLogBatchIdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutableProcessUtil.java
Labels: backport

#249 fix(bom): fix bom imports in camunda-only-bom (#4628)
  bom/operaton-only-bom/pom.xml
  clients/java/client/pom.xml
  commons/bom/pom.xml
  commons/pom.xml
  commons/typed-values/pom.xml
  connect/bom/pom.xml
  connect/pom.xml
  distro/run/core/pom.xml
  distro/tomcat/assembly/pom.xml
  distro/wildfly/modules/pom.xml
  distro/wildfly26/modules/pom.xml
  engine-dmn/engine/pom.xml
  engine-dmn/feel-api/pom.xml
  engine-dmn/feel-juel/pom.xml
  engine-plugins/connect-plugin/pom.xml
  engine-plugins/identity-ldap/pom.xml
  engine-plugins/pom.xml
  engine-plugins/spin-plugin/pom.xml
  engine-rest/engine-rest-jakarta/pom.xml
  engine-rest/engine-rest/pom.xml
  engine/pom.xml
  pom.xml
  qa/integration-tests-engine-jakarta/pom.xml
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-webapps/pom.xml
  qa/test-db-instance-migration/test-fixture-722/pom.xml
  qa/test-db-instance-migration/test-migration/pom.xml
  qa/test-old-engine/pom.xml
  qa/tomcat9-runtime/pom.xml
  spin/bom/pom.xml
  spin/pom.xml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-all/pom.xml
  spring-boot-starter/starter-qa/integration-test-plugins/spin/spin-dataformat-json-jackson/pom.xml
  spring-boot-starter/starter/pom.xml
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/pom.xml
  webapps/pom.xml
Labels: build, backport

#236 Set up nightly build
  .github/workflows/nighly-build.yml
  pom.xml
Labels: build

#250 Fix instanceof check and cast with pattern matching in spin/dataformat-json-jackson. (#85)
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/JacksonJsonDataFormat.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/TypeHelper.java
Labels: refactoring

#266 fix(build): Import operaton-commons-bom
  clients/java/client/pom.xml
Labels: build

#262 Fix nightly build
  .github/scripts/prepare-distros-archive.sh
  .github/scripts/prepare-reports.sh
  .github/workflows/build.yml
  .github/workflows/nighly-build.yml
  .gitignore
  pom.xml
Labels: build

#270 chore(sonar): Fix instanceof check and cast with pattern matching in qa
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/variables/DeserializableVariableTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/TimerExpressionBean.java
  qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/PerfTestBuilder.java
  qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/PerfTestRunner.java
  qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/framework/report/SectionedHtmlReportBuilder.java
  qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/junit/AuthHelper.java
  qa/performance-tests-engine/src/main/java/org/operaton/bpm/qa/performance/engine/junit/PerfTestProcessEngine.java
Labels: refactoring

#271 Fix instanceof check and cast with pattern matching in clients. (#85)
  clients/java/client/src/main/java/org/operaton/bpm/client/impl/ExternalTaskClientLogger.java
  clients/java/client/src/main/java/org/operaton/bpm/client/topic/impl/TopicSubscriptionManager.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/mapper/FileValueMapper.java
Labels: refactoring

#260 bugfix(test): Changed the strategy for initializing JUnit Extensions …
  clients/java/client/pom.xml
  clients/java/client/src/it/java/org/operaton/bpm/client/client/ClientIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/task/ExternalTaskCustomExtensionPropertiesIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/task/ExternalTaskHandlerIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/topic/TopicSubscriptionIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/FileSerializationIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/JavaSerializationIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/JsonSerializationIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/JsonValueIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/LocalVariableIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/PrimitiveVariableIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/XmlSerializationIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/XmlValueIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/pa/PaExceptionIT.java
  clients/java/client/src/it/java/org/operaton/bpm/client/variable/pa/PaSerializationIT.java
Labels: bug, qa

#278 feat(README): Add Slack badge
  README.md
Labels: enhancement

#279 Add AllContributors
  README.md
Labels: documentation

#284 docs: Update Readme and CONTRIBUTING.md
  .github/jreleaser/changelog.tpl
  CONTRIBUTING.md
  README.md
Labels: documentation

#290 core(build): Bump remaining modules to 1.0.0-beta-2
  distro/run/assembly/pom.xml
  distro/run/core/pom.xml
  distro/run/distro/pom.xml
  distro/run/modules/example/pom.xml
  distro/run/modules/pom.xml
  distro/run/modules/rest/pom.xml
  distro/run/modules/webapps/pom.xml
  distro/run/pom.xml
  distro/run/qa/example-plugin/pom.xml
  distro/run/qa/integration-tests/pom.xml
  distro/run/qa/pom.xml
  distro/run/qa/runtime/pom.xml
Labels: build

#286 chore(parent): Set Spring Version to 6.1.15
  parent/pom.xml
Labels: dependencies, backport-c7

#291 fix(openApi): add missing schema declarations
  engine-rest/engine-rest-openapi/README.md
  engine-rest/engine-rest-openapi/src/main/templates/lib/utils.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/external-task/{id}/errorDetails/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/external-task-log/{id}/error-details/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/history/job-log/{id}/stacktrace/get.ftl
  engine-rest/engine-rest-openapi/src/main/templates/paths/job/{id}/stacktrace/get.ftl
Labels: bug, backport-c7

#292 chore(parent): Bump Spring Libraries
  parent/pom.xml
Labels: dependencies, backport-c7

#299 Add script to update the version in all project files
  .github/scripts/set-project-version.sh
  distro/license-book/src/main/resources/license-book.txt
Labels: build

#302 chore(build): Remove obsolete relativePath declarations
  bom/operaton-bom/pom.xml
  bom/operaton-only-bom/pom.xml
  bom/pom.xml
  distro/run/assembly/pom.xml
  distro/run/core/pom.xml
  distro/run/distro/pom.xml
  distro/run/modules/oauth2/pom.xml
  distro/run/modules/pom.xml
  distro/run/modules/rest/pom.xml
  distro/run/modules/webapps/pom.xml
  distro/run/qa/example-plugin/pom.xml
  distro/run/qa/integration-tests/pom.xml
  distro/run/qa/pom.xml
  distro/run/qa/runtime/pom.xml
  engine-rest/assembly/pom.xml
  engine-rest/engine-rest-jakarta/pom.xml
  engine-rest/engine-rest-openapi-generator/pom.xml
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest/pom.xml
  examples/invoice-jakarta/pom.xml
  examples/invoice/pom.xml
  parent/pom.xml
  qa/integration-tests-webapps/integration-tests/pom.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
  test-utils/assert/core/pom.xml
  test-utils/assert/qa/pom.xml
  webapps/assembly-jakarta/pom.xml
  webapps/assembly/pom.xml
Labels: build
