Repository operaton/operaton, pull requests merged in 2025-04, with the labels that each got.

#660 fix: Fix shading of spin dataformat all artifact
  .devenv/scripts/build/build-and-run-integration-tests.sh
  jakarta-ee/ejb-client/src/main/java/org/operaton/bpm/application/impl/web/ProcessArchiveServletContextListener.java
  qa/tomcat-runtime/pom.xml
  spin/dataformat-all/pom.xml
  spin/dataformat-all/src/main/resources/META-INF/services/spinjar.javax.xml.bind.JAXBContext
  spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/DomXmlLogger.java
  spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/spi/DefaultJaxBContextProvider.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/impl/xml/dom/format/spi/DefaultJaxBContextProviderTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/format/spi/EmptyContextProvider.java
Labels: dependencies

#692 chore: Disable flaky tests
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionUserOperationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/ReducedJobExceptionLoggingTest.java
Labels: bug

#693 chore: Fix tomcat postgres integration tests
  bom/internal-dependencies/pom.xml
  parent/pom.xml
  qa/tomcat-runtime/pom.xml
Labels: qa

#694 chore: Clean up javax, migrate to jakarta
  bom/internal-dependencies/pom.xml
  commons/typed-values/.clirr-jenkins-ignore.xml
  commons/typed-values/pom.xml
  distro/jboss/webapp/src/main/webapp/WEB-INF/web.xml
  engine-plugins/connect-plugin/src/test/resources/logback-test.xml
  engine-plugins/identity-ldap/src/test/resources/logback-test.xml
  engine-plugins/spin-plugin/src/test/resources/logback-test.xml
  engine-rest/assembly/src/main/runtime/jbossas7/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/was/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/webapp/WEB-INF/weblogic.xml
  engine-rest/engine-rest/src/test/resources-jersey2/custom-date-format-web.xml
  engine-rest/engine-rest/src/test/resources-wink/custom-application-web.xml
  engine-rest/engine-rest/src/test/resources-wink/custom-date-format-web.xml
  engine-rest/engine-rest/src/test/resources-wink/default-application-web.xml
  engine/src/test/resources/logback-test.xml
  qa/integration-tests-engine/src/test/resources/logging.properties
  qa/large-data-tests/src/test/resources/logback-test.xml
  qa/performance-tests-engine/src/main/resources/logback.xml
  webapps/assembly/src/main/runtime/develop/resources/logback.xml
  webapps/assembly/src/main/webapp/WEB-INF/web.xml
  webapps/assembly/src/test/resources/logback-test.xml
Labels: refactoring

#700 chore(deps): bump to feel-scala 1.19.1
  pom.xml
Labels: dependencies, backport-c7

#702 chore: Avoid duplicate libraries in Tomcat distro
  distro/tomcat/assembly/assembly.xml
Labels: build

#703 dependencies: Upgrade Ant 1.9.16 -> 1.10.15
  bom/internal-dependencies/pom.xml
Labels: dependencies

#711 fix(tests): Fix flacky tests by avoid caching of engine.
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/BatchHistoricDecisionInstanceDeletionUserOperationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/AbstractMetricsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorExceptionLoggingHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/ReducedJobExceptionLoggingTest.java
Labels: qa

#718 fix(dependencies): Add org.glassfish.jaxb dep. to jboss-deployment-structure.xml & include into war
  qa/integration-tests-engine/src/test/java-wildfly/org/operaton/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure.xml
Labels: platform:wildfly

#727 Fix Wildfly integration tests
  qa/integration-tests-engine/src/test/java-tomcat/org/operaton/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java-wildfly-servlet/org/operaton/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java-wildfly/org/operaton/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/SpinClassloadingTest.java
  qa/integration-tests-engine/src/test/resources-wildfly/arquillian.xml
  qa/integration-tests-engine/src/test/resources-wildfly/jboss-deployment-structure-spin.xml
  qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/ejb/local/jboss-deployment-structure.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
Labels: qa

#722 Avoid tests running on port 8080
  engine-rest/engine-rest-openapi/pom.xml
  engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/BasicAuthenticationTest.java
  engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/DeploymentTest.java
  engine-rest/engine-rest-openapi/src/test/java/org/operaton/bpm/engine/rest/openapi/client/ProcessInstanceTest.java
Labels: qa, refactoring

#717 feat(rest): make LockAndFetchHandler blocking queue's capacity configurable
  engine-rest/assembly/src/main/runtime/jbossas7/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/tomcat/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/was/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/wildfly/webapp/WEB-INF/web.xml
  engine-rest/assembly/src/main/runtime/wls/webapp/WEB-INF/web.xml
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/impl/FetchAndLockHandlerImpl.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/impl/FetchAndLockHandlerTest.java
Labels: backport-c7

#730 Fix flaky MultiEngineCommandContextTest
  database/pom.xml
  engine/src/test/java/org/operaton/bpm/engine/test/logging/ProcessDataLoggingContextMultipleEnginesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/MultiEngineCommandContextTest.java
Labels: qa

#736 fix: Add `@WebListener` to InvoiceProcessApplication
  engine/src/main/java/org/operaton/bpm/application/PostDeploy.java
  engine/src/main/java/org/operaton/bpm/application/impl/ServletProcessApplication.java
  examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceProcessApplication.java
Labels: jakarta-ee

#737 fix(xtac): initialize url resolver with null base url
  clients/java/client/src/main/java/org/operaton/bpm/client/impl/ExternalTaskClientBuilderImpl.java
  clients/java/client/src/test/java/org/operaton/bpm/client/impl/ExternalTaskClientBuilderImplTest.java
Labels: backport-c7

#745 fix(engine): print correct value of processDefinitionId in toString() for events
  engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoricVariableUpdateEventEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricDetailVariableInstanceUpdateEntity.java
Labels: backport-c7

#746 fix(webapp): Handle null authentication as unauthorized
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/auth/UserAuthenticationResource.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/auth/UserAuthenticationResourceTest.java
Labels: backport-c7

#744 fix(engine): fix multi-instance collection expression evaluation
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/MultiInstanceActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ParallelMultiInstanceActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/SequentialMultiInstanceActivityBehavior.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/multiinstance/MultiInstanceTest.java
Labels: backport-c7

#749 fix(webapps/tasklist): render task if no filter exists
  webapps/frontend/ui/tasklist/client/scripts/tasklist/directives/cam-tasklist-tasks.js
Labels: lang:javascript, backport-c7

#754 chore: DeploymentBuilder: Mark enableDuplicateFiltering() for removal
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/repository/ProcessApplicationDeploymentBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentBuilder.java
  engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
Labels: deprecation

#758 chore: Replace package.html files by package-info.java
  engine/src/main/java/org/operaton/bpm/engine/delegate/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/delegate/package.html
  engine/src/main/java/org/operaton/bpm/engine/form/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/form/package.html
  engine/src/main/java/org/operaton/bpm/engine/history/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/history/package.html
  engine/src/main/java/org/operaton/bpm/engine/identity/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/identity/package.html
  engine/src/main/java/org/operaton/bpm/engine/impl/digest/_apacheCommonsCodec/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/impl/digest/_apacheCommonsCodec/package.html
  engine/src/main/java/org/operaton/bpm/engine/impl/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/impl/package.html
  engine/src/main/java/org/operaton/bpm/engine/management/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/management/package.html
  engine/src/main/java/org/operaton/bpm/engine/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/package.html
  engine/src/main/java/org/operaton/bpm/engine/query/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/query/package.html
  engine/src/main/java/org/operaton/bpm/engine/repository/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/repository/package.html
  engine/src/main/java/org/operaton/bpm/engine/runtime/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/runtime/package.html
  engine/src/main/java/org/operaton/bpm/engine/task/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/task/package.html
  engine/src/main/java/org/operaton/bpm/engine/test/package-info.java
  engine/src/main/java/org/operaton/bpm/engine/test/package.html
Labels: refactoring

#760 fix(spring-boot-webapp): resolve favicon path
  spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/FaviconResourceResolver.java
  spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/OperatonBpmWebappAutoConfiguration.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/FaviconResourceResolverTest.java
  spring-boot-starter/starter-webapp-core/src/test/java/org/operaton/bpm/spring/boot/starter/webapp/OperatonBpmWebappAutoConfigurationIntegrationTest.java
Labels: backport-c7

#770 fix: improve build resilience on osx (#769)
  engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
Labels: build, qa

#762 fix(engine): Fix nested jar loading for Spring Boot 3.2
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java
Labels: bug, backport-c7

#777 Fix Integration test execution with Postgres on Wildfly
  database/pom.xml
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/AbstractActivityLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/AbstractTaskLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/AssignTaskLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/CompleteTaskLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/CreateTaskLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/DeleteTaskLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/EndActivityLiteral.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/annotation/event/StartActivityLiteral.java
  engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
  qa/integration-tests-engine/pom.xml
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestAdditionalResourceSuffixes.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianLifecycleObserverExtension.java
  qa/integration-tests-engine/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
  qa/wildfly-runtime/src/main/common/standalone/deployments/postgresql-ds.xml
Labels: build, qa, platform:wildfly

#763 chore: use dedicated AssertJ assertion methods
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableLocalTypedTest.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableTypedTest.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/StartProcessTest.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/BeanPropertyElTest.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java
Labels: qa, refactoring

#761 chore: bump quarkus version to 3.20.0 (latest LTS)
  pom.xml
Labels: dependencies, backport-c7
