Repository operaton/operaton, pull requests merged in 2025-03, with the labels that each got.

#560 dependencies: Resolve Guava dependency
  engine/pom.xml
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java
  qa/large-data-tests/pom.xml
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
Labels: dependencies, refactoring

#557 Add Testcontainers Support for Postgres, MariaDB, MySQL
  .github/workflows/integration-tests.yml
  bom/internal-dependencies/pom.xml
  database/pom.xml
  engine/src/test/java/org/operaton/bpm/engine/test/persistence/ConnectionPersistenceExceptionTest.java
  engine/src/test/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineExtensionRequiredDatabaseTest.java
  parent/pom.xml
  qa/tomcat-runtime/pom.xml
  qa/tomcat-runtime/src/main/conf/server.xml
  test-utils/testcontainers/README.md
  test-utils/testcontainers/pom.xml
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonMSSQLContainerProvider.java
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonMariaDBContainerProvider.java
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonMySqlContainerProvider.java
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonPostgreSQLContainerProvider.java
  test-utils/testcontainers/src/main/resources/testcontainers.properties
Labels: enhancement, build

#571 chore(test): Migrate some engine JUnit4 tests to JUnit5.
  engine/src/main/junit4/org/operaton/bpm/container/impl/jmx/deployment/MockInitialContextFactory.java
  engine/src/main/junit4/org/operaton/bpm/container/impl/jmx/deployment/MockInitialContextRule.java
  engine/src/test/java/org/operaton/bpm/application/impl/context/ProcessApplicationContextTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/DeploymentRegistrationTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentProcessApplicationTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentRegistrationTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/parser/ProcessesXmlParserTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/el/ProcessApplicationElResolverTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/embedded/EmbeddedProcessApplicationTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/event/ProcessApplicationEventListenerTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/deployment/jobexecutor/PlatformJobExecutorActivateTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/deployment/jobexecutor/StartManagedThreadPoolStepTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/deployment/BpmPlatformXmlLocationTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/deployment/util/ClassPathScannerTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/deployment/util/MultipleClasspathRootsClassPathScannerTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/deployment/util/VfsProcessApplicationScannerTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/kernel/MBeanServiceContainerTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/metadata/PropertyHelperTest.java
  engine/src/test/java/org/operaton/bpm/container/impl/parser/BpmPlatformXmlParserTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/batch/BatchElementConfigurationTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/batch/BatchInvocationsPerJobByBatchTypeConfigTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/batch/BatchInvocationsPerJobByBatchTypeTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/batch/builder/BatchCalculateTotalJobsTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/cfg/CompositeProcessEnginePluginTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/runtime/DefaultDeserializationTypeValidatorTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/test/TestHelperTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/BitMaskUtilTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/ClockUtilTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/ExceptionUtilTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/ImmutablePairTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/PropertiesUtilTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/util/StringUtilTest.java
Labels: qa, refactoring

#568 Start using Oracle Testcontainer [#553]
  database/pom.xml
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
  test-utils/testcontainers/pom.xml
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonOracleContainerProvider.java
  test-utils/testcontainers/src/main/resources/META-INF/services/org.testcontainers.containers.JdbcDatabaseContainerProvider
Labels: enhancement, qa

#606 chore(dependencies): Upgrade AssertJ to 3.27
  parent/pom.xml
Labels: dependencies

#611 chore: Resolve Sonar findings
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetJobRetriesCmd.java
Labels: refactoring

#620 chore(dependencies): upgrade JUnit to 5.12.1
  bom/internal-dependencies/pom.xml
  parent/pom.xml
Labels: dependencies

#625 chore(test): Convert all tests in cmmn package to JUnit5.
  engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineTestExtension.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceHumanTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceMilestoneTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceProcessTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceStageTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceTest.java
Labels: qa, refactoring

#619 Resolve dependency on Hamcrest
  commons/logging/pom.xml
  commons/typed-values/pom.xml
  commons/utils/pom.xml
  distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/SqlAvailabilityIT.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/BusinessProcessBeanTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/ProcessVariableMapTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/BusinessKeyTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/CompleteTaskTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ExecutionIdTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessIdTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableLocalTypedTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/ProcessVariableTypedTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/StartProcessTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/api/annotation/TaskIdTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/bpmn/SignalEventTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/BusinessProcessContextConversationScopeTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/BusinessProcessContextTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/MultiInstanceDelegate.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/MultiInstanceTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/ThreadContextAssociationTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/BeanPropertyElTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/ElTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/TaskListenerInvocationTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/el/beans/CdiTaskListenerBean.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/TestEventListener.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/util/InjectCustomProcessEngineTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/util/InjectDefaultProcessEngineTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/jsf/TaskFormTest.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/experimental/ProcessVariablesTest.java
  engine-plugins/connect-plugin/pom.xml
  engine/pom.xml
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/api/authorization/util/AuthorizationScenarioInstance.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/api/authorization/util/MissingAuthorizationMatcher.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageEventSubprocessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestDeploymentTenantId.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentResumePreviousOnDeploymentName.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentResumePreviousOnProcessDefinitionKey.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/InvocationContextTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/dmn/DmnHistoryTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/SLSBExceptionInDelegateTest.java
Labels: dependencies, qa, refactoring

#633 chore: fix syntax error in integration-build.yml
  .github/workflows/integration-build.yml
Labels: build

#634 chore: Merge module distro/tomcat/webapp-jakarta
  bom/internal-dependencies/pom.xml
  distro/tomcat/assembly/src/conf/server.xml
  distro/tomcat/distro/assembly.xml
  distro/tomcat/distro/pom.xml
  distro/tomcat/pom.xml
  distro/tomcat/webapp-jakarta/pom.xml
  distro/tomcat/webapp-jakarta/src/main/webapp/WEB-INF/web.xml
  distro/tomcat/webapp/pom.xml
  distro/tomcat/webapp/src/main/webapp/WEB-INF/web.xml
Labels: refactoring

#635 chore: Merge module webapps/assembly-jakarta
  bom/operaton-only-bom/pom.xml
  distro/run/qa/example-plugin/pom.xml
  distro/webjar/pom.xml
  distro/wildfly/webapp/pom.xml
  spring-boot-starter/starter-webapp-core/pom.xml
  webapps/assembly-jakarta/assembly.xml
  webapps/assembly-jakarta/pom.xml
  webapps/assembly-jakarta/renames.properties
  webapps/assembly/pom.xml
  webapps/assembly/src/main/runtime/develop/java/org/operaton/bpm/pa/service/JaxBSerialized.java
  webapps/assembly/src/main/runtime/test/java/org/operaton/bpm/pa/rest/TestServlet.java
  webapps/pom.xml
Labels: refactoring

#615 refactor: Merge module spin/dataformat-xml-dom-jakarta
  .devenv/ide/idea/run/external-task-client_cargo-remote-debug.run.xml
  .devenv/scripts/build/build.sh
  clients/java/README.md
  clients/java/client/pom.xml
  distro/wildfly/modules/pom.xml
  engine-plugins/spin-plugin/pom.xml
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/XmlSerializationTest.java
  spin/bom/pom.xml
  spin/dataformat-all/pom.xml
  spin/dataformat-xml-dom-jakarta/pom.xml
  spin/dataformat-xml-dom/README.md
  spin/dataformat-xml-dom/pom.xml
  spin/pom.xml
Labels: refactoring

#626 chore(test): Converting more engine tests from JUnit4 to JUnit5.
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/api/runtime/migration/ProcessInstanceSnapshot.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/api/runtime/migration/ProcessInstanceSnapshotBuilder.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionAssert.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTree.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTreeAssertion.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTreeProcessDefinitionIdAssertion.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTreeStructureAssertion.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/MigratingProcessInstanceValidationReportAssert.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/MigrationPlanAssert.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/MigrationPlanValidationReportAssert.java
  engine/src/main/junit4/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTestRule.java
  engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineExtension.java
  engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/migration/MigrationTestExtension.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/AbstractAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/context/DelegateExecutionContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/context/ProcessEngineContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/delegate/DelegateExecutionHierarchyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/dmn/DecisionServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/dmn/DecisionServiceUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/encoding/ProcessEngineCharacterEncodingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskConditionsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskQueryByCreateTimeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskQueryByPriorityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskSupportTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/SetExternalTasksRetriesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/RetryIntervalsConfigurationTest.java
Labels: qa, refactoring

#655 dependencies: upgrade Spring
  bom/internal-dependencies/pom.xml
  parent/pom.xml
Labels: dependencies

#662 dependencies: Removed bouncycastle references
  bom/internal-dependencies/pom.xml
Labels: dependencies

#664 dependencies: Remove Kong Unirest (and SetupTests main Class)
  qa/integration-tests-webapps/integration-tests/pom.xml
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/SetupTests.java
Labels: dependencies, qa

#668 fix: remove broken weld dependency
  qa/integration-tests-engine/pom.xml
Labels: dependencies

#672 Upgrade mysql connector
  .devenv/scripts/build/build-and-run-integration-tests.sh
  .github/workflows/integration-build.yml
  database/pom.xml
Labels: dependencies

#676 chore: Move BOMs to /bom module
  bom/commons/pom.xml
  bom/connect/pom.xml
  bom/pom.xml
  bom/spin/pom.xml
  commons/pom.xml
  connect/pom.xml
  spin/pom.xml
Labels: build
