Repository operaton/operaton, pull requests merged in 2025-08, with the labels that each got.

#1033 build(wildfly): Remove /lib folder from distro
  distro/wildfly/assembly/assembly.xml
Labels: build

#1037 build(dependencis): Upgrade to Tomcat 11.0.9
  bom/internal-dependencies/pom.xml
  engine-rest/engine-rest/pom.xml
  parent/pom.xml
  webapps/assembly/pom.xml
Labels: dependencies

#1015 Fix Tomcat distro
  distro/tomcat/distro/assembly.xml
  engine/src/main/resources/META-INF/services/jakarta.servlet.ServletContainerInitializer
Labels: bug

#1047 Update xmlns for assembly.xml files
  distro/license-book/assembly.xml
  distro/run/assembly/assembly.xml
  distro/run/distro/assembly.xml
  distro/sql-script/assembly.xml
  distro/tomcat/assembly/assembly.xml
  distro/tomcat/distro/assembly.xml
  distro/wildfly/assembly/assembly.xml
  distro/wildfly/distro/assembly.xml
  engine-rest/assembly/assembly-classes.xml
  engine-rest/assembly/assembly-sources.xml
  engine-rest/assembly/assembly-tests.xml
  engine-rest/assembly/assembly-war-tomcat.xml
  engine-rest/assembly/assembly-war-wildfly.xml
  webapps/assembly/assembly.xml
Labels: refactoring

#1050 chore(deps): Pin Groovy version for Wildfly modules
  distro/wildfly/modules/pom.xml
Labels: distro:wildfly

#1057 chore: Update Tomcat container id to tomcat11x
  clients/java/client/pom.xml
  distro/tomcat/distro/pom.xml
  qa/integration-tests-webapps/shared-engine/pom.xml
Labels: distro:tomcat

#1058 fix(tomcat): Remove WebListener annotation
  engine/src/main/java/org/operaton/bpm/application/impl/ServletProcessApplication.java
  examples/invoice/src/main/java/org/operaton/bpm/example/invoice/InvoiceProcessApplication.java
Labels: bug, jakarta-ee, distro:tomcat

#1070 feat: Database migration tests with PostgreSQL, MySQL, MariaDB, Oracl…
  .github/workflows/migration-test.yml
  database/pom.xml
  qa/test-database-container/README.md
  qa/test-database-container/docker-compose.yaml
  qa/test-database-container/my.cnf
  qa/test-database-container/test.sh
Labels: build, qa

#1083 chore(build): Ignore JRuby 10 for versions-maven-plugin
  pom.xml
Labels: build

#1079 chore(deps): Upgrade Groovy to 4.0.28
  parent/pom.xml
Labels: dependencies

#1085 chore(deps): Upgrade Liquibase to 4.33.0
  database/pom.xml
  pom.xml
Labels: dependencies

#1087 chore(deps): Upgrade jackson-databind-nullable from 0.2.6 to 0.2.7
  engine-rest/engine-rest-openapi/pom.xml
Labels: dependencies

#1088 chore(deps): Upgrade org.eclipse.angus:jakarta.mail from 2.0.3 to 2.0.4
  bom/internal-dependencies/pom.xml
Labels: dependencies

#1093 chore(deps): Upgrade commons-io to 2.20.0
  bom/internal-dependencies/pom.xml
Labels: dependencies

#1097 refactor(class-to-record): Refactor Property*Key classes to records
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/Properties.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyKey.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyListKey.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/PropertyMapKey.java
  engine/src/main/java/org/operaton/bpm/engine/impl/event/EventHandlerImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/externaltask/LockedExternalTaskImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExternalTaskEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationCancelActivity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/operation/PvmAtomicOperationCreateConcurrentExecution.java
Labels: refactoring

#1101 feat(build): Add rewrite.yml
  rewrite.yml
Labels: enhancement, build

#1124 feat: upgrade JDBC drivers to latest versions
  .github/jreleaser/changelog.tpl
  database/pom.xml
  qa/tomcat-runtime/pom.xml
  qa/wildfly-runtime/src/main/common/modules/com/microsoft/sqlserver/mssql-jdbc/main/module.xml
  qa/wildfly-runtime/src/main/common/modules/com/mysql/mysql-connector-j/main/module.xml
  qa/wildfly-runtime/src/main/common/modules/com/oracle/database/jdbc/ojdbc11/main/module.xml
  qa/wildfly-runtime/src/main/common/modules/org/mariadb/jdbc/mariadb-java-client/main/module.xml
Labels: dependencies, database:oracle, database:sqlserver, database:mysql, database:mariadb

#1148 fix: Update tomcat-jdbc and tomcat-juli dependencies versions
  qa/performance-tests-engine/pom.xml
Labels: dependencies

#1158 refactor: move anonymous Collection in OperatonListImpl to inner class
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/operaton/OperatonListImpl.java
Labels: refactoring, java

#1149 refactor(frontend): remove unused extract-loader dependency
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: dependencies

#1192 chore(rest): fix deleteProcessDefinition description [#1166]
  engine-rest/engine-rest-openapi/src/main/templates/paths/process-definition/{id}/delete.ftl
Labels: documentation, backport:c7

#1188 refactor: remove string concatenation from StringBuilder.append() calls
  clients/java/client/src/it/java/org/operaton/bpm/client/rule/EngineRule.java
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/config/ManagedProcessEngineMetadata.java
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/ProcessApplicationDeploymentService.java
  engine/src/main/java/org/operaton/bpm/container/impl/ContainerIntegrationLogger.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/ExecutionTreeProcessDefinitionIdAssertion.java
  engine/src/test/java/org/operaton/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/XmlListSerializable.java
  webapps/assembly/src/main/runtime/test/java/org/operaton/bpm/pa/rest/TestServlet.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/engine/WebappsDatabaseNamingConsistencyTest.java
Labels: refactoring, java

#1195 Junit4 Assert to AssertJ
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/optimize/OptimizeCompletedHistoricIncidentRestServiceTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/optimize/OptimizeOpenHistoricIncidentRestServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageBoundaryEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/shell/ShellTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/ActivityInstanceVerification.java
Labels: qa, refactoring
