Repository operaton/operaton, pull requests merged in 2025-06, with the labels that each got.

#866 chore: Adjust modifiers or names to match naming conventions
  clients/java/client/src/test/java/org/operaton/bpm/client/variable/DateValueMapperTest.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/AbstractHttpRequest.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpResponseImpl.java
  distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/AbstractWebIT.java
  distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/PluginsRootResourceIT.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/ProblemDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/EmptyHalCollection.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/EmptyHalResource.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/HalResource.java
  engine/src/main/java/org/operaton/bpm/engine/impl/AbstractDefinitionDeployer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/batch/RestartProcessInstancesBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/parser/HistoryParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/transformer/CmmnHistoryTransformListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AcquireJobsRunnable.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/MessageAddedNotification.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/SequentialJobAcquisitionRunnable.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/ScopeImpl.java
  engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupSchedulerCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/HistoricRootProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyEndTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupRemovalTimeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerActivityInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAttachmentsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerBatchesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerCommentsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerDecisionsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerDetailsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerExternalTaskLogsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerIdentityLinkLogsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerIncidentsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerJobLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerProcessInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerTaskMetricsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerUserOperationLogsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/HistoryCleanupSchedulerVariableInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricExternalTaskLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RootProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/builtin/PostParseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/builtin/PreParseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/builtin/TestTaskListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/decisiontask/DmnDecisionTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/partitioning/SkipHistoryOptimisticLockingExceptionsDisabledTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricCaseActivityInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricExternalTaskLogQuerySortingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/PartitioningTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/useroperationlog/UserOperationLogAnnotationTest.java
  examples/invoice/src/main/java/org/operaton/bpm/example/invoice/service/ArchiveInvoiceService.java
  examples/invoice/src/main/java/org/operaton/bpm/example/invoice/service/NotifyCreditorService.java
  model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn/util/ParseCmmnModelRule.java
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/DeleteDeploymentCascadeTest.java
  webapps/assembly/src/main/java/org/operaton/bpm/cockpit/plugin/test/AbstractCockpitPluginTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/admin/plugin/base/AbstractAdminPluginTest.java
Labels: refactoring

#869 fix: Replaced printStackTrace with a log message
  distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunDeploymentConfiguration.java
Labels: refactoring

#880 chore: Remove redundant modifiers
  engine/src/main/java/org/operaton/bpm/container/impl/spi/ServiceTypes.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/OptimizePermissions.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/Permissions.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/ProcessDefinitionPermissions.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/ProcessInstancePermissions.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/SystemPermissions.java
  engine/src/main/java/org/operaton/bpm/engine/authorization/UserOperationLogCategoryPermissions.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/BaseCallableElement.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoryEventTypes.java
  engine/src/main/java/org/operaton/bpm/engine/repository/ResourceTypes.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/kernel/util/TestServiceType.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/TestPermissions.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/bean/BusinessInterface.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/bean/StartProcessInterface.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/remote/bean/BusinessInterface.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/beans/InvocationCounterService.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/request/beans/InvocationCounterServiceLocal.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/engine/AbstractScriptEngineFactory.java
  spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/filter/LazyDelegateFilter.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/Ordering.java
Labels: refactoring

#879 feat(build): Verify library versions in Wildfly modules
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/validate-modules.sh
Labels: build

#881 chore: Avoid Double-Brace-Initialization
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/ResourceTypeUtil.java
  juel/src/main/java/org/operaton/bpm/impl/juel/SimpleResolver.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/headersec/HttpHeaderSecurityFilter.java
Labels: refactoring

#759 feat(queryAPI): add filter for instances with jobs retrying in java API
  engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/resources/org/operaton/bpm/engine/test/api/history/testInstancesWithJobsRetrying.bpmn20.xml
Labels: backport-c7

#768 chore: bump GraalVM version to 21.3.14
  parent/pom.xml
Labels: dependencies

#890 Skip nightly builds with no recent changes
  .github/workflows/integration-build.yml
Labels: build

#893 build(deps): Upgrade to Spring 6.2.8
  bom/internal-dependencies/pom.xml
Labels: dependencies

#907 refactor: Remove empty default constructors
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/execution/CaseExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/CmmnHandlerContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/PermissionCheck.java
  engine/src/main/java/org/operaton/bpm/engine/impl/dmn/entity/repository/DecisionDefinitionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/event/HistoricFormPropertyEventEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/TxContextCommandContextFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobHandlerConfiguration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IncidentStatisticsEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/ExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/management/TablePage.java
  jakarta-ee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/outbound/JcaExecutorServiceManagedConnectionFactory.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/beans/RetryConfig.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/classes/MyPojo.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/dataformat/CustomDataFormatConfigurator.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spring/beans/RetryConfig.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/classes/MyPojo.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/property/EventingProperty.java
Labels: refactoring

#908 refactor: Make methods of Session empty default methods
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/Session.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/AbstractManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/DeploymentManager.java
Labels: refactoring

#912 refactor(engine): Default methods for BpmnParseListener.
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/event/CdiEventSupportBpmnParseListener.java
  engine-plugins/connect-plugin/src/main/java/org/operaton/connect/plugin/impl/ConnectorParseListener.java
  engine/src/main/java/org/operaton/bpm/application/impl/event/ProcessApplicationEventParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/AbstractBpmnParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/DefaultFailedJobParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/parser/HistoryParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/metrics/parser/MetricsBpmnParseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/builtin/PostParseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/builtin/PreParseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionCreationAndDeletionWithParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionCreationBothAsyncWithParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionCreationWithParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionDeletionWithParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/deploy/BPMNParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/deploy/TestBPMNParseListener.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/PublishDelegateParseListener.java
Labels: refactoring

#926 task(webapp): execution metrics page, adjust month column (#5033)
  webapps/frontend/public/app/admin/locales/de.json
  webapps/frontend/public/app/admin/locales/en.json
  webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.html
  webapps/frontend/ui/admin/client/scripts/pages/execution-metrics.js
Labels: backport-c7

#925 feat(webapps): localisation for instances with jobs retrying (#4959)
  webapps/frontend/public/app/cockpit/locales/de.json
  webapps/frontend/public/app/cockpit/locales/en.json
Labels: backport-c7

#921 feat(cockpit): Make default value for cascade flag configurable (#4964)
  webapps/frontend/public/app/cockpit/scripts/config.js
  webapps/frontend/ui/cockpit/client/scripts/repository/deployments/plugins/actions/delete/modals/cam-cockpit-delete-deployment-modal-ctrl.js
  webapps/frontend/ui/common/scripts/services/cam-configuration.js
Labels: backport-c7

#922 feat(webapps): auto format expanded edit field (#4963)
  webapps/frontend/operaton-commons-ui/lib/widgets/inline-field/dialog/controller.js
Labels: backport-c7

#932 fix: AsyncContinuationJobHandler#tokenizeJobConfiguration did not fail for invalid argument
  engine/pom.xml
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandler.java
  engine/src/test/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandlerTest.java
Labels: bug

#910 refactor: Make JobHandler#onDelete default method
  engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchMonitorJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchSeedJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AsyncContinuationJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ProcessEventJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerChangeJobDefinitionSuspensionStateJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerChangeProcessDefinitionSuspensionStateJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/TimerEventJobHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/historycleanup/HistoryCleanupJobHandler.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetExceptionHandler.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetHandler.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/TweetNestedCommandExceptionHandler.java
Labels: refactoring

#937 build(deps): bump SpringBoot version to 3.5.3
  parent/pom.xml
  pom.xml
Labels: dependencies

#938 fix(deps): Override commons-compress to 1.27.1
  bom/internal-dependencies/pom.xml
Labels: dependencies

#939 Add unit test for CronExpression
  engine/src/test/junit5/org/operaton/bpm/engine/impl/calendar/CronExpressionTest.java
Labels: qa

#952 feat(engine-plugins): Support FEEL Scala Engine (#5018)
  engine-dmn/feel-scala/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  engine-plugins/spin-plugin/src/main/resources/META-INF/services/org.camunda.feel.valuemapper.CustomValueMapper
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/FeelContextDelegate.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/FeelEngineTest.java
  qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-input-output.bpmn
  qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-json-decision.dmn
  qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-process.bpmn
  qa/integration-tests-engine/src/test/resources/org/operaton/bpm/integrationtest/functional/spin/feel/feel-spin-xml-decision.dmn
Labels: backport-c7
