Repository operaton/operaton, pull requests merged in 2025-01, with the labels that each got.

#390 refactor(tests): JUnit 5 migration of module test-utils/testcontainers
  test-utils/testcontainers/pom.xml
  test-utils/testcontainers/src/test/java/org/operaton/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
Labels: qa, refactoring

#392 chore: Fix instanceof check and cast with pattern matching
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/json/ListJacksonJsonTypeDetector.java
  commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/Variables.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/util/LoggingInterceptor.java
  engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/SpinValueSerializer.java
  engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/runtime/modification/StartTransitionInstructionDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/exception/ExceptionHandlerHelper.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/util/InjectionUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/SingleQueryVariableValueCondition.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/EventSubscriptionDeclaration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/SentryHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/StageItemHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/transformer/CmmnTransform.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/variable/VariableUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/producer/DefaultDmnHistoryEventProducer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/MigrationPlanBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/VariableInstanceEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/AbstractSerializableValueSerializer.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/cleanup/CustomHistoryLevelRemovalTime.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetHistoricVariableUpdatesForOptimizeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstantiationWithVariablesInReturnTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricDetailQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/RecordingAcquireJobsRunnable.java
  spin/core/src/test/java/org/operaton/spin/impl/test/ScriptEngineRule.java
  spin/core/src/test/java/org/operaton/spin/impl/test/ScriptExtension.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/ListJacksonJsonTypeDetector.java
  spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/OperatonEventingIT.java
  webapps/assembly/src/main/java/org/operaton/bpm/cockpit/rest/dto/AbstractRestQueryParametersDto.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/rest/dto/AbstractRestQueryParametersDto.java
Labels: refactoring

#399 Upgrade SpringBoot 3.3.6 to 3.4.1
  clients/java/client/pom.xml
  distro/run/assembly/resources/keystore.p12
  distro/run/assembly/resources/production.yml
  distro/run/core/pom.xml
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/util/TestUtils.java
  distro/run/core/src/test/resources/application-test-https-enabled.yml
  distro/run/core/src/test/resources/keystore.p12
  engine-rest/engine-rest-openapi/pom.xml
  internal-dependencies/pom.xml
  parent/pom.xml
  spring-boot-starter/starter-client/spring-boot/src/test/java/org/operaton/bpm/client/spring/boot/starter/it/ClientAutoConfigurationIT.java
  spring-boot-starter/starter-client/spring-boot/src/test/java/org/operaton/bpm/client/spring/boot/starter/subscription/MergeSubscriptionConfigurationTest.java
  spring-boot-starter/starter-security/pom.xml
Labels: dependencies

#381 chore: Mark methods operatonAsync for removal & resolve usages
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractCallActivityBuilder.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractStartEventBuilder.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractSubProcessBuilder.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/builder/AbstractTaskBuilder.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/CallActivityImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/ParallelGatewayImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/StartEventImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/SubProcessImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/TaskImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/CallActivity.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/ParallelGateway.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/StartEvent.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/SubProcess.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/Task.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
Labels: refactoring

#405 refactor(engine): changes multiline strings to text blocks
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ConfigurationLogger.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/EnginePersistenceLogger.java
Labels: refactoring

#396 Re-brand "Operaton Run"
  distro/run/assembly/assembly.xml
  distro/run/assembly/pom.xml
  distro/run/assembly/resources/run.bat
  distro/run/assembly/resources/run.sh
  distro/run/core/pom.xml
  distro/run/core/src/main/java/org/operaton/bpm/run/OperatonApp.java
  distro/run/core/src/main/resources/banner.txt
  distro/run/core/src/test/java/org/operaton/bpm/run/test/AbstractRestTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/TelemetryDataTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/filter/DefaultTaskFilterTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/identity/AdminAuthorizationConfigurationTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/identity/DemoUserConfigurationTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/identity/LdapConfigurationTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/plugins/OperatonAppProcessEnginePluginsHelperTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/plugins/OperatonRunProcessEnginePluginsRegistrationTest.java
  distro/run/core/src/test/java/org/operaton/bpm/run/test/plugins/ProcessEnginePluginsConfigurationOverrideTest.java
  distro/run/distro/pom.xml
  jreleaser.yml
  spring-boot-starter/starter-client/spring-boot/src/main/resources/banner.txt
Labels: refactoring

#414 refactor(tests): Testing exceptions with only one possible invocation throwing
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ActivityStatisticsAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ConditionStartEventAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DeploymentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessDefinitionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessInstanceCommentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/SingleProcessInstanceModificationAsyncAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/batch/HistoricBatchQueryAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricDecisionInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricProcessInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricTaskInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricVariableInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoryCleanupAuthorizationTest.java
Labels: qa, refactoring

#409 refactor: Use StringUtils#hasText(), ObjectUtils#isEmpty, String#isEmpty
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/ProcessVariables.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/NamedProcessEngineServicesProducer.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/StartProcessInterceptor.java
  engine/src/main/java/org/operaton/bpm/container/impl/jmx/MBeanServiceContainer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/JakartaTransactionProcessEngineConfiguration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/JtaProcessEngineConfiguration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/DeleteTaskCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentBpmnModelInstanceCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessDiagramCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessDiagramLayoutCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentProcessModelCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetFormKeyCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetJobDuedateCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/cmd/GetDeploymentCaseDiagramCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/CallingTaskItemHandler.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/StringUtil.java
  engine/src/test/java/org/operaton/bpm/application/impl/embedded/EmbeddedProcessApplicationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramRetrievalTest.java
  javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java
Labels: refactoring

#374 chore(engine): Resolve & document deprecations in TransitionImpl, ScopeImpl
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/CdiEventSupportBpmnParseListener.java
  engine/src/main/java/org/operaton/bpm/application/impl/event/ProcessApplicationEventParseListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/ProcessDefinitionBuilder.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/ScopeImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/TransitionImpl.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/entity/EntitySerializationTest.java
Labels: refactoring

#420 chore: bump npm and node version (#402)
  parent/pom.xml
Labels: dependencies, build

#416 Chore/replace field injection with constructor injection
  distro/run/core/src/main/java/org/operaton/bpm/run/OperatonBpmRunRestConfiguration.java
  distro/run/modules/example/src/main/java/org/operaton/bpm/run/example/invoice/Application.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/BusinessProcess.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/CurrentProcessInstance.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/ProcessVariables.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/compat/FoxTaskForm.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/compat/OperatonTaskForm.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/ProcessVariableLocalMap.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/ProcessVariableMap.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/CompleteTaskInterceptor.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/StartProcessInterceptor.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/ConversationScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/DefaultContextAssociationManager.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/RequestScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/ScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/jsf/TaskForm.java
  engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/SpringProcessEngineServicesConfiguration.java
  spring-boot-starter/starter-client/spring-boot/src/main/java/org/operaton/bpm/client/spring/boot/starter/impl/PropertiesAwareClientFactory.java
  spring-boot-starter/starter-client/spring/src/main/java/org/operaton/bpm/client/spring/impl/subscription/SpringTopicSubscriptionImpl.java
  spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/OperatonBpmWebappAutoConfiguration.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/OperatonBpmAutoConfiguration.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/SpringBootProcessApplication.java
Labels: refactoring

#415 refactor(tests): Refactor ProcessInstanceAuthorizationTest
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessInstanceAuthorizationTest.java
Labels: qa, refactoring

#423 chore(tests): Simplify AssertJ assertions
  commons/logging/src/test/java/org/operaton/commons/logging/MdcAccessTest.java
  commons/testing/src/test/java/org/operaton/commons/testing/ProcessEngineLoggingRuleTest.java
  commons/utils/src/test/java/org/operaton/commons/utils/IoUtilTest.java
  commons/utils/src/test/java/org/operaton/commons/utils/StringUtilTest.java
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/api/DmnDecisionResultTest.java
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/api/DmnDecisionTableResultTest.java
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/delegate/DmnDecisionEvaluationListenerTest.java
  engine-plugins/identity-ldap/src/test/java/org/operaton/bpm/identity/impl/ldap/LdapGroupLargeQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CaseDefinitionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CaseInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DecisionDefinitionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DecisionRequirementsDefinitionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/EventSubscriptionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/FilterRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/FilterRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/JobDefinitionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/JobRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessDefinitionRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricActivityInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricCaseActivityInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricCaseInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDecisionInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricDetailRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricExternalTaskLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricIdentityLinkLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricIncidentRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricJobLogRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricTaskInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricVariableInstanceRestServiceQueryTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/autodeployment/SpringAutoDeployTest.java
  engine-spring/core/src/test/java/org/operaton/bpm/engine/spring/test/transaction/SpringTransactionIntegrationDeploymentFailTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/SchemaLogQueryAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/SchemaLogQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/telemetry/TelemetryDynamicDataTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/MultiTenancyUserOperationLogQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyCaseInstanceCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyUserOperationLogTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetHistoricOperationLogsForOptimizeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingLicenseKeyAccessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogQueryTest.java
Labels: qa, refactoring

#424 chore(tests): Join multiple assertions
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/api/DmnDecisionResultTest.java
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/api/DmnDecisionTableResultTest.java
  engine-plugins/identity-ldap/src/test/java/org/operaton/bpm/identity/impl/ldap/LdapUserQueryTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/EmptyProcessesXmlTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/InstallationCfgTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentMultipleProcessingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceGetTelemetryDataTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/license/LicenseKeyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/MultiTenancyStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricExternalTaskLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetHistoricDecisionInstancesForOptimizeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstantiationAtStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/DelegateTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/deployment/BpmnDeploymentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventConcurrencyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerEventLifecycleTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/processtask/ProcessTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ConcurrentInstallationIdInitializationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/dmn/HistoricDecisionInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/persistence/DatabaseNamingConsistencyTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/ReferenceTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/ModelTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/testmodel/instance/BirdTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/ManagedJobExecutorTest.java
  spin/core/src/test/java/org/operaton/spin/spi/DataFormatLoadingTest.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeCreateTest.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeEditListPropertyScriptTest.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeSetPropertyScriptTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomCreateTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/IncidentRestServiceTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessDefinitionResourceTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessInstanceResourceTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessInstanceRestServiceTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/IncidentRestServiceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessInstanceResourceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessInstanceRestServiceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/IncidentRestServiceTenantCheckTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessDefinitionResourceTenantCheckTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceResourceTenantCheckTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/tenantcheck/ProcessInstanceRestServiceTenantCheckTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/filter/csrf/CsrfPreventionFilterAppPathTest.java
Labels: qa, refactoring

#425 chore: Replace Collections#EMPTY_[LIST|SET|MAP]
  distro/run/core/src/main/java/org/operaton/bpm/run/property/OperatonBpmRunProcessEnginePluginProperty.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/HasDbReferences.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/StartProcessVariableScope.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskEntity.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java
  spin/core/src/main/java/org/operaton/spin/DataFormats.java
Labels: refactoring

#426 refactor(tests): Simplify chained AssertJ assertions to dedicated assertion
  commons/utils/src/test/java/org/operaton/commons/utils/IoUtilTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/db/SchemaLogUpgradeScriptPatternTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/variables/FileValueSerializerTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/ResourceRolesTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/validation/ValidateProcessTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/StringUtilTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/instance/ModelElementInstanceTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/type/child/ChildElementCollectionTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/type/reference/ReferenceTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineConfigurationConfigTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/config/OperatonEngineJobExecutorConfigTest.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeEditListPropertyScriptTest.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeEditListPropertyTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathScriptTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathTest.java
  spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/jdbc/HistoryLevelDeterminatorJdbcTemplateImplTest.java
Labels: qa, refactoring

#428 refactor: Combine semantically equal catch blocks
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java
  commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java
  distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/MscExecutorService.java
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/TypedValueAssert.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/converter/JacksonAwareStringToTypeConverter.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/converter/PeriodUnitConverter.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/task/impl/TaskResourceImpl.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/PostDeployInvocationStep.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/PreUndeployInvocationStep.java
  engine/src/main/java/org/operaton/bpm/engine/impl/RepositoryServiceImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/CaseExecutionCommandBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/SentryHandler.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/TypedValueAssert.java
  model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/test/AbstractModelElementInstanceTest.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/JacksonJsonDataFormatReader.java
  spin/dataformat-xml-dom/src/main/java/org/operaton/spin/impl/xml/dom/format/DomXmlDataFormatReader.java
Labels: refactoring

#430 refactor(tests): Remove unnecessary usage of Mockito.eq()
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/MigrationRestServiceInteractionTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/GroupAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/AuthorizationCheckRevokesCfgTest.java
Labels: qa, refactoring

#433 refactor(tests): Replace try/catch by assertThatThrownBy
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/TaskAuthorizationTest.java
Labels: qa, refactoring

#434 refactor: Resolve deprecation of Class#newInstance
  commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java
  engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/spin/SpinValueMapperFactory.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/AbstractSearchQueryDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/security/auth/ProcessEngineAuthenticationFilter.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/jobexecutor/StartJobAcquisitionStep.java
  engine/src/main/java/org/operaton/bpm/engine/impl/DefaultArtifactFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/validator/FormValidators.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/GenericManagerFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/ReflectUtil.java
  webapps/assembly/src/main/java/org/operaton/bpm/cockpit/rest/dto/AbstractRestQueryParametersDto.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/auth/ContainerBasedAuthenticationFilter.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/rest/dto/AbstractRestQueryParametersDto.java
Labels: refactoring, deprecation

#435 Refactor/deprecation/1
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/MessageRestServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceSyncTest.java
Labels: qa, refactoring, deprecation

#432 refactor(tests): Testing exceptions with only one possible invocation throwing
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DatabaseHistoryPropertyAutoTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DatabaseTableSchemaTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/PersistenceExceptionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceHumanTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceMilestoneTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceProcessTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceStageTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/dmn/DecisionServiceTest.java
Labels: qa, refactoring

#418 refactor(tests): Testing exceptions with only one possible invocation throwing
  engine/src/test/java/org/operaton/bpm/application/impl/context/ProcessApplicationContextTest.java
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/parser/ProcessesXmlParserTest.java
  engine/src/test/java/org/operaton/bpm/engine/impl/incident/CompositeIncidentHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DatabaseHistoryPropertyAutoTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/PersistenceExceptionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/BuiltInValidatorsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormDataTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java
Labels: qa, refactoring

#437 refactor(tests): Add assertions to test case
  distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/webapps/LoginIT.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/impl/task/CdiTaskServiceTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/UserRestServiceInteractionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/DeploymentCacheCfgTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/variables/JavaSerializationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/variables/scope/TargetVariableScopeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/common/AbstractProcessEngineServicesAccessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingVariableFetchingAndDeletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/MultiEngineCommandContextTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/BpmnDiTest.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/CreateModelTest.java
  model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn/CreateModelTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/spring/timer/SpringServletPATimerStartEventExpressionTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/LoginIT.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/engine/test/junit5/deployment/EnsureDbCleanTest.java
Labels: qa, refactoring

#440 refactor: Resolve deprecation usage ParseException#getResorceReports
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/ParseExceptionDto.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/DeploymentRestServiceInteractionTest.java
  engine/src/main/java/org/operaton/bpm/engine/ParseException.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/AsyncAfterTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/ConditionalStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/link/LinkEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageBoundaryEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageIntermediateEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventParseInvalidProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/external/ExternalTaskParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/EventBasedGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/job/JobPrioritizationBpmnConstantValueTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/transaction/TransactionSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskResultMappingTest.java
Labels: deprecation

#441 refactor(tests): Replace try/catch by assertThatThrownBy
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
Labels: qa, refactoring

#442 refactor: Resolve usage of deprecated API
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/event/AbstractCdiEventListener.java
  engine-rest/engine-rest-openapi-generator/src/main/java/org/operaton/bpm/engine/rest/openapi/generator/impl/TemplateParser.java
Labels: refactoring

#444 build: Trigger docker image build on release
  .github/workflows/release-publish.yml
Labels: build

#445 build: Fix release-publish.yml
  .github/workflows/release-publish.yml
Labels: build

#446 build: Fix release-publish.yml
  .github/workflows/release-publish.yml
Labels: build

#443 refactor: Resolve Sonar warnings
  commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/impl/VariableMapImpl.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/AbstractVariableMap.java
  engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/el/VariableContextScriptBindings.java
  engine-dmn/engine/src/test/java/org/operaton/bpm/dmn/engine/delegate/DmnDecisionEvaluationListenerTest.java
  engine-dmn/feel-scala/src/main/java/org/operaton/bpm/dmn/feel/impl/scala/function/builder/CustomFunctionBuilderImpl.java
  engine-plugins/identity-ldap/src/main/java/org/operaton/bpm/identity/impl/ldap/LdapIdentityProviderSession.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine/src/main/java/org/operaton/bpm/application/AbstractProcessApplication.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/scanning/ClassPathProcessApplicationScanner.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/calendar/CronExpression.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/SynchronousOperationLogProducer.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/AcquiredJobs.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/plugin/AdministratorAuthorizationPlugin.java
  engine/src/main/java/org/operaton/bpm/engine/impl/scripting/engine/ScriptBindings.java
  engine/src/main/java/org/operaton/bpm/engine/impl/xml/ProblemImpl.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerEventLifecycleTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/handler/CaseHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorBatchTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/GroovyAsyncScriptExecutionTest.java
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/format/TypeHelper.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/actuator/JobExecutorHealthIndicator.java
Labels: refactoring

#448 build: Trigger Docker build
  .github/workflows/nighly-build.yml
  .github/workflows/release-publish.yml
  .github/workflows/release.yml
Labels: enhancement, build

#449 build: Fix docker trigger
  .github/workflows/nighly-build.yml
Labels: build

#451 chore: Remove unnecessary throws declarations
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/HistoricVariableJsonSerializationTest.java
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/variables/JavaSerializationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/variables/FileValueSerializerTest.java
  javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/inflow/JobExecutionHandlerActivation.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatConfiguratorJodaTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatConfiguratorTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/plugin/resource/AbstractAppPluginRootResourceTest.java
Labels: refactoring

#452 chore: Avoid using boxed "Boolean" types directly in boolean expressions
  clients/java/client/src/it/java/org/operaton/bpm/client/util/TestUtil.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
  engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java
  engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/metrics/parser/MetricsExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
  engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/context/ProcessEngineContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SendMessageDelegate.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutionTree.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java
  javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java
  juel/src/main/java/org/operaton/bpm/impl/juel/AstChoice.java
  juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/JacksonJsonNode.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/query/JacksonJsonPathQuery.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeSetPropertyTest.java
  spring-boot-starter/starter-client/spring-boot/src/main/java/org/operaton/bpm/client/spring/boot/starter/impl/PropertiesAwareClientFactory.java
  spring-boot-starter/starter-client/spring/src/main/java/org/operaton/bpm/client/spring/impl/client/ClientFactory.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/SpringBootProcessApplication.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultProcessEngineConfiguration.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/EventPublisherPlugin.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/PublishDelegateParseListener.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/test/util/JobExecutorHelper.java
Labels: refactoring

#456 chore: Revert "chore: Avoid using boxed "Boolean" types directly in boolean expressions (#452)
  clients/java/client/src/it/java/org/operaton/bpm/client/util/TestUtil.java
  engine-cdi/core/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
  engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java
  engine/src/main/java/org/operaton/bpm/engine/impl/TaskQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/diagram/ProcessDiagramLayoutFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/metrics/parser/MetricsExecutionListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
  engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/BooleanValueSerializer.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/context/ProcessEngineContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SendMessageDelegate.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ExecutionTree.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java
  javaee/jobexecutor-ra/src/main/java/org/operaton/bpm/container/impl/threading/ra/JcaExecutorServiceConnector.java
  juel/src/main/java/org/operaton/bpm/impl/juel/AstChoice.java
  juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/JacksonJsonNode.java
  spin/dataformat-json-jackson/src/main/java/org/operaton/spin/impl/json/jackson/query/JacksonJsonPathQuery.java
  spin/dataformat-json-jackson/src/test/java/org/operaton/spin/json/tree/JsonTreeSetPropertyTest.java
  spring-boot-starter/starter-client/spring-boot/src/main/java/org/operaton/bpm/client/spring/boot/starter/impl/PropertiesAwareClientFactory.java
  spring-boot-starter/starter-client/spring/src/main/java/org/operaton/bpm/client/spring/impl/client/ClientFactory.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/SpringBootProcessApplication.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultProcessEngineConfiguration.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/EventPublisherPlugin.java
  spring-boot-starter/starter/src/main/java/org/operaton/bpm/spring/boot/starter/event/PublishDelegateParseListener.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/test/util/JobExecutorHelper.java
Labels: refactoring

#371 tests(starter): add tests for oauth2 and identity (fixes #175)
  spring-boot-starter/starter-security/pom.xml
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/SampleApplication.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/AbstractSpringSecurityIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSampleApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSecurityAutoConfigOauth2ApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OperatonIdentityProviderIT.java
  spring-boot-starter/starter-security/src/test/resources/oauth2-mock.properties
Labels: backport-c7

#429 refactor: Make logger instances final
  commons/logging/src/test/java/org/operaton/commons/logging/ExampleLogger.java
  connect/core/src/main/java/org/operaton/connect/Connectors.java
  connect/core/src/main/java/org/operaton/connect/impl/ConnectLogger.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/AbstractHttpConnector.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/HttpLogger.java
  connect/http-client/src/main/java/org/operaton/connect/httpclient/impl/util/ParseUtil.java
  connect/soap-http-client/src/main/java/org/operaton/connect/httpclient/soap/impl/SoapHttpLogger.java
  engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/DmnLogger.java
  engine-dmn/feel-juel/src/main/java/org/operaton/bpm/dmn/feel/impl/juel/FeelLogger.java
  engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/SpringBeansResolverFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/BpmnActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ExclusiveGatewayActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/InclusiveGatewayActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/deployer/BpmnDeployer.java
Labels: refactoring

#461 fix(wildfly): Add missing modules for Spring dependencies
  distro/wildfly/modules/pom.xml
  distro/wildfly/modules/src/main/modules/org/operaton/bpm/operaton-engine/main/module.xml
  distro/wildfly/modules/src/main/modules/org/springframework/spring-core/main/module.xml
  distro/wildfly/modules/src/main/modules/org/springframework/spring-jcl/main/module.xml
Labels: bug

#411 security: Sanitize message parameters to avoid injection attacks
  commons/logging/src/main/java/org/operaton/commons/logging/BaseLogger.java
  commons/logging/src/test/java/org/operaton/commons/logging/BaseLoggerTest.java
Labels: enhancement

#467 chore: Update maven plugins
  engine-rest/engine-rest-openapi/pom.xml
  parent/pom.xml
  pom.xml
  qa/integration-tests-engine-jakarta/src/test/java/org/operaton/bpm/integrationtest/util/DeploymentHelper.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentWithProcessEnginePlugin.java
  webapps/pom.xml
Labels: dependencies, build

#470 chore: resolve issues reported by SonarQube
  engine/src/main/java/org/operaton/bpm/container/impl/jmx/MBeanServiceContainer.java
Labels: refactoring

#471 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ActivityStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/BatchQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/queries/BoundedNumberOfMaxResultsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CaseExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CaseInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CreateAndResolveIncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/AsyncAfterTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityDelegateMappingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CaseCallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/compensate/CompensationEventParseInvalidProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/BoundaryConditionalEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/casetask/CaseTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/cmmn10/Cmmn10CompatibilityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/deployment/CmmnDeployerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/AcquirableJobCacheTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/CommandContextInterceptorTest.java
Labels: refactoring

#469 chore: Convert tests to JUnit 5.
  commons/testing/src/main/java/org/operaton/commons/testing/ProcessEngineLoggingRule.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/AbstractSpringSecurityIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSampleApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSecurityAutoConfigOauth2ApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OperatonIdentityProviderIT.java
Labels: qa, refactoring

#473 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/GroupQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/EventSubscriptionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/EventSubProcessStartConditionalEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/EventBasedGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/el/ExpressionBeanAccessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/FullHistoryTest.java
Labels: refactoring

#478 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTenantTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobEntityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/IncidentQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/IntermediateConditionalEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/job/JobPrioritizationBpmnConstantValueTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/job/JobPrioritizationBpmnExpressionValueTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/servicetask/JavaServiceTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/InterruptingEventSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java
Labels: qa, refactoring

#477 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricProcessInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricBatchQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricActivityInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricCaseActivityInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricCaseActivityStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricCaseInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIncidentQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/dmn/HistoricDecisionInstanceQueryTest.java
Labels: qa, refactoring

#480 refactor: Resolve Sonar warnings
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormDataTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryCleanupTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyProcessInstantiationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyExternalTaskCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyFormServiceCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ModificationExecutionSyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceSyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/TransientVariableTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/external/ExternalTaskParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/TaskDueDateExtensionsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/TaskFollowUpDateExtensionsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/deployment/CmmnDeployerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/humantask/HumanTaskFollowUpDateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingMessageCorrelationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/dmn/deployment/DecisionDefinitionDeployerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricCaseActivityStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricDetailQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogTestByXml.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricVariableInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionCreationAndDeletionWithParseListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/CustomHistoryLevelIdentityLinkTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java
Labels: refactoring
