Repository operaton/operaton, pull requests merged in 2025-05, with the labels that each got.

#778 fix: failing IdGeneratorDataSourceTest
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/IdGeneratorDataSourceTest.java
  engine/src/test/resources/org/operaton/bpm/engine/test/api/cfg/IdGeneratorDataSourceTest.testIdGeneratorDataSource.bpmn20.xml
Labels: qa

#780 Build: Fix integration build
  .github/workflows/integration-build.yml
Labels: build

#796 build(deps): Upgrade to Spring 6.2.6 & SpringBoot 3.4.5
  bom/internal-dependencies/pom.xml
  parent/pom.xml
Labels: dependencies

#773 Add generic to classes and methods
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/DefaultValueMappers.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/ValueMappers.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/VariableValue.java
  engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/transform/DefaultElementTransformHandlerRegistry.java
  engine-plugins/spin-plugin/src/main/java/org/operaton/spin/plugin/impl/feel/integration/SpinValueMapper.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/EmptyHalCollection.java
Labels: refactoring

#804 chore: Extract constants for query parameters
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/AbstractManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AttachmentManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/AuthorizationManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/BatchManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ByteArrayManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/CommentManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/EventSubscriptionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExternalTaskManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricActivityInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricBatchManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseActivityInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricCaseInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricDetailManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricExternalTaskLogManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricIdentityLinkLogManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricIncidentManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricJobLogManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricTaskInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricVariableInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IdentityInfoManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IdentityLinkManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobDefinitionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/MeterLogManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ProcessDefinitionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/UserOperationLogManager.java
Labels: refactoring

#808 Backport: chore(pom): add support for Spring Boot 3.4.1
  distro/run/core/src/test/java/org/operaton/bpm/run/test/config/https/HttpsConfigurationEnabledTest.java
  distro/run/core/src/test/resources/application-test-https-enabled.yml
  engine-rest/engine-rest/pom.xml
Labels: backport-c7

#787 refactor(tests): remove duplicate waitForJobExecutorToProcessAllJobs …
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/context/ThreadContextAssociationTest.java
  engine-cdi/src/test/java/org/operaton/bpm/engine/cdi/test/impl/event/EventNotificationTest.java
  engine-spring/pom.xml
  engine-spring/src/test/java/org/operaton/bpm/engine/spring/test/components/jobexecutor/SpringJobExecutorTest.java
  engine-spring/src/test/java/org/operaton/bpm/engine/spring/test/transaction/SpringTransactionIntegrationTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/test/TestHelper.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/util/JobExecutorWaitUtils.java
  engine/src/main/junit4/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
  engine/src/main/junit4/org/operaton/bpm/engine/test/util/ProcessEngineTestRule.java
  engine/src/main/junit5/org/operaton/bpm/engine/test/junit5/ProcessEngineTestExtension.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/ExclusiveJobAcquisitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobDefinitionFunctionalTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCleanupTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/SequentialJobAcquisitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/JobExecutorWaitUtils.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingByJobPriorityTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/TransactionIntegrationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/ManagedJobExecutorTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/ManagedJobExecutorTest.java
  quarkus-extension/engine/deployment/src/test/java/org/operaton/bpm/quarkus/engine/test/persistence/TransactionIntegrationTest.java
  quarkus-extension/engine/qa/src/test/java/org/operaton/bpm/engine/cdi/test/CdiProcessEngineTestCase.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/test/util/JobExecutorHelper.java
Labels: qa, refactoring

#680 dependency: update dmn-js
  webapps/frontend/package-lock.json
  webapps/frontend/package.json
Labels: dependencies

#822 chore: Removed implementations of getFeatureDescriptors
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/el/CdiResolver.java
  engine-spring/src/main/java/org/operaton/bpm/engine/spring/ApplicationContextElResolver.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/AbstractElResolverDelegate.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/ReadOnlyMapELResolver.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/VariableContextElResolver.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/VariableScopeElResolver.java
  engine/src/main/java/org/operaton/bpm/engine/test/mock/MockElResolver.java
  juel/src/main/java/org/operaton/bpm/impl/juel/RootPropertyResolver.java
  juel/src/main/java/org/operaton/bpm/impl/juel/SimpleResolver.java
Labels: refactoring, deprecation

#824 fix(build): Ensure that main jar does not contain test classes.
  engine-cdi/pom.xml
  engine-plugins/connect-plugin/pom.xml
  engine-plugins/pom.xml
  engine-plugins/spin-plugin/src/test/java/org/operaton/spin/plugin/script/SpinJRubyScriptTaskTest.java
  engine-spring/pom.xml
  engine-spring/src/main/java/org/operaton/bpm/engine/spring/SpringExpressionManager.java
  engine/pom.xml
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/el/JuelExpressionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/mock/MockElResolver.java
  engine/src/main/java/org/operaton/bpm/engine/impl/mock/MockExpressionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/mock/Mocks.java
  engine/src/main/java/org/operaton/bpm/engine/impl/mock/MocksResolverFactory.java
  engine/src/main/java/org/operaton/bpm/engine/test/api/runtime/migration/ProcessInstanceSnapshot.java
  engine/src/main/java/org/operaton/bpm/engine/test/api/runtime/migration/ProcessInstanceSnapshotBuilder.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/Deployment.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/RequiredHistoryLevel.java
  engine/src/main/junit-shared/org/operaton/bpm/engine/test/package-info.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/context/DelegateExecutionContextTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/filter/FilterTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mock/MocksTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/el/ExpressionManagerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  qa/integration-tests-engine/pom.xml
  quarkus-extension/engine/deployment/pom.xml
  quarkus-extension/engine/qa/pom.xml
  spring-boot-starter/starter-test/src/main/java/org/operaton/bpm/spring/boot/starter/test/helper/StandaloneInMemoryTestConfiguration.java
  test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessEngineTestsJobTest.java
  test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessInstanceAssertJobTest.java
  webapps/assembly/pom.xml
Labels: build

#825 chore(tests): Fix test dependencies
  .gitignore
  qa/integration-tests-engine/src/test/java-wildfly/org/operaton/bpm/integrationtest/util/TestContainer.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/callbacks/EjbPALifecycleCallbacksTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestAdditionalResourceSuffixes.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestCustomProcessesXmlFileLocation.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/cfg/TestDeploymentTenantId.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/ear/TestFoxPlatformClientAsEjbModule_onePaAsLib.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/ear/TestFoxPlatformClientAsEjbModule_pasAsEjbModule.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/ear/TestFoxPlatformClientAsEjbModule_twoPasAsLib.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/ear/TestPaAnnotatedEjb.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/ear/TestPaAsEjbJar.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestResourceName.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentCustomPAName.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/deployment/war/TestWarDeploymentDeployChangedOnlyWithJarAsLib.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiBeanCallActivityResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiBeanResolutionOnDeploymentTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiBeanResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiBeanSignallableActivityBehaviorResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiCallActivityVersionTagTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/cdi/CdiDelegateBeanResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/deployment/RedeployCaseClassloadingTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/deployment/RedeployProcessClassloadingTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/ear/TestJavaDelegateResolution_ClientAsLibInWebModule.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/variables/DeserializableVariableTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/CaseExecutionListenerResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/CaseVariableListenerResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/JavaDelegateResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/SignallableActivityBehaviorResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/war/TaskListenerResolutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/InvocationContextTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/SetVariablesMigrationContextSwitchTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSFSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSLSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/local/LocalSingletonBeanInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/remote/RemoteSFSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/remote/RemoteSLSBInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/remote/RemoteSingletonBeanInvocationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/error/CatchErrorFromProcessApplicationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/event/CdiProcessApplicationEventSupportTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/event/ProcessApplicationExecutionListenerTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/event/ProcessApplicationTaskListenerTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/metadata/engine/TestProcessEnginesXmlInProcessApplication.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/migration/MigrationContextSwitchBeansTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/migration/MigrationContextSwitchClassesTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/modification/ModificationContextSwitchTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/GroovyAsyncScriptExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/PaLocalScriptEngineCallActivityConditionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatAndPostDeployTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatConfiguratorFailingTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spin/PaDataFormatProviderTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spring/SpringExpressionResolvingTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/spring/SpringPAExpressionResolvingTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/AsyncJobExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/ManagedJobExecutorTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/SetVariablesAsyncTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/AbstractFoxPlatformIntegrationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/DeploymentHelper.java
Labels: qa

#826 chore: Make interface methods to default methods which are marked for removal
  engine/src/main/java/org/operaton/bpm/engine/history/HistoricVariableInstance.java
  engine/src/main/java/org/operaton/bpm/engine/impl/DeploymentQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/transformer/AbstractCmmnTransformListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/transformer/CmmnTransformListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/transformer/CmmnHistoryTransformListener.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricVariableInstanceEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/repository/DeploymentBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/repository/ProcessApplicationDeploymentBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentBuilder.java
  engine/src/main/java/org/operaton/bpm/engine/repository/DeploymentQuery.java
  engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/deploy/TestCmmnTransformListener.java
Labels: deprecation

#829 chore(model-api): Unnecessary Modifier
  model-api/cmmn-model/src/main/java/org/operaton/bpm/model/cmmn/instance/IfPart.java
Labels: refactoring

#836 chore(commons): Unnecessary Modifier
  commons/typed-values/src/main/java/org/operaton/bpm/engine/variable/type/ValueType.java
  commons/utils/src/main/java/org/operaton/commons/utils/cache/Cache.java
Labels: refactoring

#848 refactor(tests): Convert tests to JUnit5.
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrateEventSubProcessAndTriggerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrateSuspendedInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationActiveEventSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationAddBoundaryEventsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationAddMultiInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationAddSubprocessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationBoundaryEventsParameterizedTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationBoundaryEventsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationCallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationCompensationAddRemoveSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationCompensationAddSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationCompensationRemoveSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationCompensationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationEventBasedGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationEventSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationExternalTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationFlipScopesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationHorizontalScopeChangeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationIncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationIntermediateConditionalEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationMessageCatchEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationMessageStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationMultiInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationNestedEventSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationPlanCreationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationPlanGenerationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationReceiveTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationRemoveBoundaryEventsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationRemoveMultiInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationRemoveSubprocessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationSignalCatchEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationSignallableServiceTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTimerBoundryEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTimerCatchEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTransactionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationTransitionInstancesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationUserTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationVariablesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationWithoutTriggerConditionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/SetProcessDefinitionVersionCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/SetVariablesMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationHistoryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchMigrationUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchSetVariablesMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/history/MigrationHistoricActivityInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/history/MigrationHistoricIncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/history/MigrationHistoricProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/history/MigrationHistoricTaskInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/history/MigrationHistoricVariablesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/util/ConditionalEventFactory.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/util/MessageEventFactory.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/util/MigratingBpmnEventTriggerAssert.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/util/SignalEventFactory.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/util/TimerEventFactory.java
Labels: qa, refactoring
