Repository operaton/operaton, pull requests merged in 2025-02, with the labels that each got.

#481 refactor: Simplify assertions
  engine/src/test/java/org/operaton/bpm/engine/impl/util/ImmutablePairTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cfg/ForceCloseMybatisConnectionPoolTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/delegate/DelegateExecutionHierarchyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/DeploymentStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/MetricsIntervalTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RedeploymentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationCancellationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstantiationAtActivitiesHistoryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstantiationWithVariablesInReturnTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/conditional/ConditionalStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageEventSubprocessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageNonInterruptingBoundaryEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageStartEventSubscriptionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/message/MessageStartEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/iomapping/InputOutputTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/parse/BpmnParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/receivetask/ReceiveTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/shell/ShellTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/processtask/ProcessTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/repetition/RepetitionRuleTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricActivityInstanceStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorShutdownTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/entity/ExecutionSequenceCounterTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/FullHistoryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/scripting/ScriptEngineCachingTest.java
Labels: qa, refactoring

#482 refactor: Rename constants
  clients/java/client/src/main/java/org/operaton/bpm/client/impl/EngineClient.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/CustomJacksonDateFormatTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/FilterRestServiceInteractionTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/calendar/DurationHelper.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/GroupAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/StandaloneTaskGetVariableAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/HandleTaskAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskReadPermissionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/ProcessTaskReadVariablePermissionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskReadPermissionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/getvariable/StandaloneTaskReadVariablePermissionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/updatevariable/ProcessTaskAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/task/updatevariable/StandaloneTaskAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/AuthorizationServiceAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceAuthorizationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetHistoricIdentityLinkLogsForOptimizeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/diagram/ProcessDiagramParseTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricIdentityLinkLogTest.java
  spin/dataformat-xml-dom/src/test/java/org/operaton/spin/xml/dom/XmlDomXPathScriptTest.java
Labels: refactoring

#483 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/DeleteProcessDefinitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/DeploymentQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RedeploymentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/decisiontask/DmnDecisionTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/dmn/businessruletask/DmnBusinessRuleTaskResultMappingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/dmn/deployment/DecisionDefinitionDeployerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricTaskDurationReportTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricTaskInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricTaskReportTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricVariableInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/DeploymentAwareJobExecutorTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/history/HistoricTaskInstanceQueryTest.java
Labels: qa, refactoring

#431 refactor: Replace this "Map.get()" and condition with a call to "Map.computeIfAbsent()"
  engine-dmn/engine/src/main/java/org/operaton/bpm/dmn/engine/impl/el/DefaultScriptEngineResolver.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/hal/HalLinker.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/runtime/impl/FilterResourceImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/ActivityExecutionTreeMapping.java
  engine/src/main/java/org/operaton/bpm/engine/impl/batch/BatchElementConfiguration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/standalone/StandaloneTransactionContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/entity/runtime/CaseExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/execution/CaseExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/model/CmmnSentryDeclaration.java
  engine/src/main/java/org/operaton/bpm/engine/impl/core/model/CoreModelElement.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/cache/DbEntityCache.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSessionFactory.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/CommandContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/DeploymentEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/process/ProcessDefinitionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/scripting/env/ScriptingEnvironment.java
  engine/src/main/java/org/operaton/bpm/engine/impl/test/TestHelper.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/ClassNameUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/CollectionUtil.java
  model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/ModelImpl.java
  model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/validation/ValidationResultsCollectorImpl.java
  webapps/assembly/src/main/java/org/operaton/bpm/admin/impl/DefaultAdminRuntimeDelegate.java
  webapps/assembly/src/main/java/org/operaton/bpm/cockpit/impl/DefaultCockpitRuntimeDelegate.java
Labels: refactoring

#487 fix: Adjust versioning scheme for SQL scripts package
  .github/workflows/integration-tests.yml
  .github/workflows/nighly-build.yml
  .github/workflows/release.yml
  jreleaser.yml
  spring-boot-starter/starter-security/pom.xml
Labels: build

#488 chore: complete assertions
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/ProcessDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  model-api/xml-model/src/test/java/org/operaton/bpm/model/xml/type/child/ChildElementCollectionTest.java
Labels: refactoring

#475 chore: suppress warnings for intended fallthrough to default in switch
  juel/src/main/java/org/operaton/bpm/impl/juel/Parser.java
Labels: refactoring

#489 chore: improves findings reported by SonarQube
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/BpmPlatformParser1_1.java
  distro/wildfly26/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/BpmPlatformParser1_1.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/repository/ProcessApplicationDeploymentBuilder.java
Labels: refactoring

#490 refactor: resolve Sonar warnings
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/json/JacksonJsonDataFormat.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/util/PathUtil.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/util/URLEncodingUtil.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/PathUtilTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/util/URLEncodingUtilTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/AbstractNativeQuery.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/entity/runtime/CaseExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/form/engine/HtmlElementWriter.java
  engine/src/main/java/org/operaton/bpm/engine/impl/history/SetRemovalTimeToHistoricProcessInstancesBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/JakartaTransactionInterceptor.java
  engine/src/main/java/org/operaton/bpm/engine/impl/interceptor/JtaTransactionInterceptor.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TaskEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/CollectionUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/LogUtil.java
  engine/src/test/java/org/operaton/bpm/container/impl/jmx/kernel/MBeanServiceContainerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/MultiTenancyTaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskEventsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/escalation/EscalationEventParseInvalidProcessTest.java
  juel/src/main/java/org/operaton/bpm/impl/juel/Builder.java
  juel/src/main/java/org/operaton/bpm/impl/juel/ExpressionFactoryImpl.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSampleApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/OperatonBpmSecurityAutoConfigOauth2ApplicationIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OAuth2GrantedAuthoritiesMapperIT.java
  spring-boot-starter/starter-security/src/test/java/org/operaton/bpm/spring/boot/starter/security/oauth2/impl/OperatonIdentityProviderIT.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/CsrfPreventionFilter.java
Labels: refactoring

#491 refactor: Extract method calls in try-blocks within tests to variables
  engine/src/test/java/org/operaton/bpm/application/impl/deployment/RedeploymentProcessApplicationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/RetrieveOperatonFormRefTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/BulkHistoryDeleteTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryCleanupTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/batch/BatchSetRemovalTimeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTenantTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/SuspendJobDefinitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/metrics/MetricsIntervalTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyMessageCorrelationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricActivityInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/interceptor/CommandContextInterceptorTest.java
Labels: qa, refactoring

#495 Fix nightly build
  .github/workflows/nighly-build.yml
  .github/workflows/release.yml
Labels: bug, build

#496 refactor: Code of a lambda to have only one invocation possibly throwing a runtime exception
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/RetrieveOperatonFormRefTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/identity/IdentityServiceUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ActivateJobDefinitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancySignalReceiveTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/MultiTenancyDecisionRequirementsDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyProcessDefinitionSuspensionStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/suspensionstate/MultiTenancyProcessInstanceSuspensionStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyActivityCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyDeploymentCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyExecutionVariableCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyExternalTaskCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyFormServiceCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyFormVariablesCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyHistoricDataCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyIdentityLinkCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageCorrelationCmdTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMessageEventReceivedCmdTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyMigrationExecuteTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyProcessDefinitionCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyProcessInstanceCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancySignalReceiveCmdTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyStartProcessInstanceByConditionCmdTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyTaskServiceCmdsTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/tenantcheck/MultiTenancyUserOperationLogTenantCheckTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/CaseDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/DecisionDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/HistoryTimeToLiveDeploymentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/ProcessDefinitionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/ProcessDefinitionSuspensionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/CorrelateAllMessageBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ExecutionQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/MessageCorrelationByLocalVariablesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryOrTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceSuspensionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RestartProcessInstanceSyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceAsyncOperationsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SetVariablesBatchTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/TransientVariableTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateAsyncTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/UpdateProcessInstancesSuspendStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/message/MessageCorrelationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationBoundaryEventsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationEventSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/MigrationIntermediateConditionalEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/SetProcessDefinitionVersionCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/batch/BatchSetVariablesMigrationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryExpressionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryOrTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
Labels: qa, refactoring

#497 dependencies: Upgrade slf4j and logback
  internal-dependencies/pom.xml
  parent/pom.xml
  test-utils/assert/core/pom.xml
  test-utils/assert/qa/pom.xml
  test-utils/testcontainers/pom.xml
  webapps/assembly/pom.xml
Labels: dependencies

#493 chore: use try-with-resources
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/serializable/SerializableDataFormat.java
  clients/java/client/src/main/java/org/operaton/bpm/client/variable/impl/format/xml/DomXmlDataFormat.java
  commons/utils/src/main/java/org/operaton/commons/utils/IoUtil.java
  engine-plugins/identity-ldap/src/test/java/org/operaton/bpm/identity/ldap/util/LdapTestEnvironment.java
  engine/src/main/java/org/operaton/bpm/engine/impl/ant/DeployBarTask.java
  engine/src/main/java/org/operaton/bpm/engine/impl/ant/LaunchThread.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/behavior/ShellActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cfg/ProcessEngineConfigurationImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/IoUtil.java
  engine/src/main/java/org/operaton/bpm/engine/impl/variable/serializer/JavaObjectSerializer.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/variables/JavaSerializationTest.java
  juel/src/main/java/org/operaton/bpm/impl/juel/ExpressionFactoryImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/Bpmn.java
  model-api/cmmn-model/src/main/java/org/operaton/bpm/model/cmmn/Cmmn.java
  model-api/dmn-model/src/main/java/org/operaton/bpm/model/dmn/Dmn.java
  model-api/xml-model/src/main/java/org/operaton/bpm/model/xml/impl/util/IoUtil.java
  spin/core/src/main/java/org/operaton/spin/impl/util/SpinIoUtil.java
  spring-boot-starter/starter-webapp-core/src/main/java/org/operaton/bpm/spring/boot/starter/webapp/filter/ResourceLoadingProcessEnginesFilter.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/filter/SecurityFilterRulesTest.java
Labels: refactoring

#367 chore(engine): add debug logs to improve job acquisition job execution logging
  engine-spring/core/src/main/java/org/operaton/bpm/engine/spring/components/jobexecutor/SpringJobExecutor.java
  engine/src/main/java/org/operaton/bpm/container/impl/jmx/services/JmxManagedThreadPool.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobExecutor.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobExecutorLogger.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/RuntimeContainerJobExecutor.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/SequentialJobAcquisitionRunnable.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ThreadPoolJobExecutor.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/DelayDelegate.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobAcquisitionLoggingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutionLoggingTest.java
  engine/src/test/resources/org/operaton/bpm/engine/test/jobexecutor/SimpleAsyncDelayProcess.bpmn20.xml
Labels: backport-c7

#505 refactor: Remove unused local variables & cleanup
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableLocalRestResourceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskVariableRestResourceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/UserOperationLogRestServiceQueryTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/DbSqlSession.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricExternalTaskLogAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/cmmn/CaseServiceCaseTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/externaltask/ExternalTaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/RemovalTimeStrategyStartTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/TenantIdProviderTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/optimize/GetRunningHistoricProcessInstancesForOptimizeTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/message/MessageCorrelationUserOperationLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/migration/SetProcessDefinitionVersionCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskVariablesTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventPayloadTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/receivetask/ReceiveTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/transaction/TransactionSubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/tasklistener/TaskListenerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/usertask/UserTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/cmmn10/Cmmn10CompatibilityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/operation/CaseExecutionCompletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/processtask/ProcessTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/repetition/RepetitionRuleTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/stage/AutoCompleteTest.java
  test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/ProcessInstanceAssertIsWaitingForTest.java
Labels: refactoring

#369 fix(asyncInstanceModification): respect ancestor during startBefore/after cmd execution (#4829)
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractInstantiationCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/json/ModificationCmdJsonConverter.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/SingleProcessInstanceModificationAsyncTest.java
  engine/src/test/resources/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceModificationTest.loop.bpmn
Labels: backport-c7

#508 feat(test): New ParameterizedTestExtension
  test-utils/junit5-extension/src/main/java/org/operaton/bpm/engine/test/junit5/ParameterizedTestExtension.java
  test-utils/junit5-extension/src/test/java/org/operaton/bpm/dmn/engine/test/junit5/ParameterizedTestExtensionTest.java
Labels: enhancement

#517 build: Improve Integration Test pipeline
  .github/workflows/integration-tests.yml
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/BusinessProcess.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/CurrentProcessInstance.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/ProcessVariables.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/compat/FoxTaskForm.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/compat/OperatonTaskForm.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/CompleteTaskInterceptor.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/StartProcessInterceptor.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/ConversationScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/DefaultContextAssociationManager.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/RequestScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/impl/context/ScopedAssociation.java
  engine-cdi/core/src/main/java/org/operaton/bpm/engine/cdi/jsf/TaskForm.java
  pom.xml
  qa/README.md
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/classloading/jobexecution/ClassloadingDuringJobExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/ejb/SLSBExceptionInDelegateTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/migration/MigrationContextSwitchBeansTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/scriptengine/GroovyAsyncScriptExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/AsyncJobExecutionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/AsyncJobExecutionWithRollbackTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/FailedJobCommandTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/JobPrioritizationFailureTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/JobPrioritizationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/TimerRecalculationTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/DemoVariableClass.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/ManagedJobExecutorBean.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/PriorityBean.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/SampleServiceBean.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/TimerExpressionBean.java
  qa/integration-tests-webapps/shared-engine/pom.xml
Labels: build

#510 fix(webapps): add skipIsolationLevelCheck to configuration on webapp init
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/db/QuerySessionFactory.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/db/QuerySessionFactoryTest.java
  webapps/assembly/src/test/resources/operaton-skip-check.cfg.xml
Labels: backport-c7

#526 chore: add assertions to tests
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/UserRestServiceInteractionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/IncidentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/repository/RepositoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/task/TaskServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/signal/SignalEventReceivedBuilderTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/property/PropertyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceDurationReportTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorPriorityRangeConfigurationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/entity/JobEntityTest.java
  freemarker-template-engine/pom.xml
  freemarker-template-engine/src/test/java/org/operaton/templateengines/engine/FreeMarkerScriptEngineTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/AsyncJobExecutionTest.java
Labels: qa, refactoring

#509 fix(webapps/assembly): Fix selectPDStatistics Query
  webapps/assembly/src/main/resources/org/operaton/bpm/cockpit/plugin/base/queries/processDefinition.xml
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/ProcessDefinitionRestServiceTest.java
Labels: bug, backport-c7

#535 chore(build): Rework build setup of engine-dmn / JUnit 5
  engine-dmn/engine/pom.xml
  engine-dmn/engine/src/main/junit4/org/operaton/bpm/dmn/engine/test/DmnEngineRule.java
  engine-dmn/engine/src/main/junit4/org/operaton/bpm/dmn/engine/test/DmnEngineTestRule.java
  engine-dmn/engine/src/main/junit5/org/operaton/bpm/dmn/engine/test/DecisionResource.java
  engine-dmn/engine/src/main/junit5/org/operaton/bpm/dmn/engine/test/DmnEngineExtension.java
  engine-dmn/engine/src/main/junit5/org/operaton/bpm/dmn/engine/test/DmnEngineTestExtension.java
  engine-dmn/engine/src/test/junit4/org/operaton/bpm/dmn/engine/test/DmnEngineRuleTest.java
  engine-dmn/engine/src/test/junit5/org/operaton/bpm/dmn/engine/test/DmnEngineExtensionTest.java
  pom.xml
  test-utils/junit5-extension-dmn/README.md
  test-utils/junit5-extension-dmn/pom.xml
  test-utils/junit5-extension-dmn/src/main/java/org/operaton/bpm/dmn/engine/test/junit5/DmnEngineExtension.java
  test-utils/junit5-extension-dmn/src/test/java/org/operaton/bpm/dmn/engine/test/junit5/DmnEngineExtensionTest.java
  test-utils/junit5-extension-dmn/src/test/java/org/operaton/bpm/dmn/engine/test/junit5/RegisterDmnEngineExtensionTest.java
  test-utils/junit5-extension-dmn/src/test/resources/logback-test.xml
  test-utils/junit5-extension-dmn/src/test/resources/org/operaton/bpm/dmn/engine/test/junit5/DecisionWithLiteralExpression.dmn
Labels: qa, refactoring

#534 Move internal-dependencies (fixes #533)
  bom/internal-dependencies/pom.xml
  database/pom.xml
  pom.xml
  webapps/assembly/pom.xml
Labels: build, refactoring

#542 refactor(build): Add internal-dependencies as module to bom/pom.xml
  bom/pom.xml
  pom.xml
Labels: build

#543 fix(build): Remove junit5-extension-dmn from root pom.xml
  pom.xml
Labels: build

#547 refactor: Move classes junit4 source folder
  engine/src/main/junit4/org/operaton/bpm/engine/impl/test/AbstractProcessEngineTestCase.java
  engine/src/main/junit4/org/operaton/bpm/engine/impl/test/PluggableProcessEngineTestCase.java
  engine/src/main/junit4/org/operaton/bpm/engine/impl/test/PvmTestCase.java
  engine/src/main/junit4/org/operaton/bpm/engine/test/ProcessEngineRule.java
  engine/src/main/junit4/org/operaton/bpm/engine/test/ProcessEngineTestCase.java
Labels: qa, refactoring

#558 refactor: Replace stream.collect(Collectors.toList()) by stream.toList()
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/deployment/processor/ProcessApplicationProcessor.java
  qa/test-db-instance-migration/test-migration/src/test/java/org/operaton/bpm/qa/upgrade/scenarios7210/jobexecutor/ExclusiveOverProcessHierarchiesTest.java
Labels: refactoring
