Repository operaton/operaton, pull requests merged in 2025-09, with the labels that each got.

#1199 Backport "fix(engine) Add space in validateServiceTaskLike error message (#5357)"
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
Labels: backport:c7

#1205 refactor(logging): Refactor logging arguments with concatenated strings
  distro/run/core/src/test/java/org/operaton/bpm/run/test/util/LoggingInterceptor.java
  distro/run/qa/integration-tests/src/test/java/org/operaton/bpm/run/qa/util/SpringBootManagedContainer.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/util/CreationalContextReleaseListener.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DefaultUserPermissionNameForTaskCfgTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/mail/EmailTestCase.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/operation/CaseExecutionStateTransitionCollector.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/AbstractCompetingTransactionsOptimisticLockingTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingActivityInstanceCancellationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingForkTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingJobAcquisitionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingJoinTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingParentCompletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingProcessCompletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSentrySatisfactionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSignalsTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSubprocessCompletionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/CompetingSuspensionTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ConcurrentVariableUpdateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ControllableThread.java
  engine/src/test/java/org/operaton/bpm/engine/test/logging/LogEngineNameDelegate.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/EventCollector.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/pvm/activities/ParallelGateway.java
Labels: refactoring

#1189 feat(api): filter process instances by rootProcessInstanceId [#1162]
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/history-process-instance.ftl
  engine-rest/engine-rest-openapi/src/main/templates/lib/commons/process-instance-query-params.ftl
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/history/HistoricProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/runtime/ProcessInstanceQueryDto.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/ProcessInstanceRestServiceQueryTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/helper/MockProvider.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceQueryTest.java
  engine/src/main/java/org/operaton/bpm/engine/history/HistoricProcessInstanceQuery.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/ProcessInstanceQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/runtime/ProcessInstanceQuery.java
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Execution.xml
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/ProcessInstanceQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
Labels: backport:c7

#1224 refactor(unused-params): Remove unused method parameters
  distro/run/core/src/main/java/org/operaton/bpm/run/utils/OperatonBpmRunProcessEnginePluginHelper.java
  engine-cdi/src/main/java/org/operaton/bpm/engine/cdi/impl/annotation/StartProcessInterceptor.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/IncidentRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskRestServiceInteractionTest.java
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/TaskRestServiceQueryTest.java
  engine/src/main/java/org/operaton/bpm/container/impl/deployment/StartProcessEngineStep.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetUserAccountCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetUserInfoCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/behavior/CmmnBehaviorLogger.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/behavior/StageOrTaskActivityBehavior.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ExecuteJobHelper.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/ExecuteJobsRunnable.java
  engine/src/main/java/org/operaton/bpm/engine/impl/mock/MockExpressionManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/IdentityInfoManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/ReflectUtil.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/AuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DeploymentAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/DeploymentStatisticsAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/ProcessDefinitionAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/authorization/history/HistoricActivityInstanceAuthorizationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyProcessInstantiationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/message/MessageCorrelationTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/concurrency/ConcurrentJobExecutorTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/logging/ProcessDataLoggingContextTest.java
  jakarta-ee/ejb-service/src/main/java/org/operaton/bpm/container/impl/ejb/JobExecutionHandlerMDB.java
  juel/src/main/java/org/operaton/bpm/impl/juel/AstUnary.java
  juel/src/main/java/org/operaton/bpm/impl/juel/BooleanOperations.java
  model-api/bpmn-model/src/test/java/org/operaton/bpm/model/bpmn/OperatonExtensionsTest.java
  spin/core/src/main/java/org/operaton/spin/impl/SpinFactoryImpl.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/SecurityFilter.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/AuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/IncidentRestServiceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessDefinitionResourceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessDefinitionRestServiceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessInstanceResourceAuthorizationTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/cockpit/plugin/base/authorization/ProcessInstanceRestServiceAuthorizationTest.java
Labels: refactoring

#1239 build(deps): bump Quarkus 3.26.1 -> 3.26.2
  pom.xml
Labels: dependencies

#1244 Backport camunda 3366f1b467
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/Resource.xml
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/MultiTenancyRepositoryServiceTest.java
Labels: backport:c7, database

#1242 Task #1180 : Backport HistoricInstanceQueries : orQuery with multiple states or withIncident
  engine-rest/engine-rest/src/test/java/org/operaton/bpm/engine/rest/history/HistoricProcessInstanceRestServiceInteractionTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/EnsureUtil.java
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricProcessInstance.xml
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceQueryOrTest.java
Labels: backport:c7

#1264 fix(wildfly): MscExecutorService has to update lastWarningLogged after logging
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/service/MscExecutorService.java
Labels: bug, distro:wildfly

#1257 Resolve HTTPClient 4 dependency
  bom/internal-dependencies/pom.xml
  distro/run/qa/integration-tests/pom.xml
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/handler/JobExecutorAdd.java
  parent/pom.xml
  qa/integration-tests-webapps/integration-tests/pom.xml
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/AbstractWebIntegrationTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/AbstractWebappUiIntegrationTest.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/CsrfPreventionIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/DateSerializationIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/ErrorPageIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/ExceptionLoggerIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/HttpHeaderSecurityIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/PluginsRootResourceIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/SessionCookieSameSiteIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/SessionCookieSecurityIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/TestProperties.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestIT.java
  qa/integration-tests-webapps/integration-tests/src/main/java/org/operaton/bpm/rest/RestJaxRs2IT.java
  qa/integration-tests-webapps/pom.xml
  spring-boot-starter/starter-qa/integration-test-webapp/runtime/pom.xml
  spring-boot-starter/starter/src/test/java/org/operaton/bpm/spring/boot/starter/configuration/impl/DefaultDatasourceConfigurationTest.java
Labels: dependencies, refactoring, backport:c7, java

#1271 refactor(tests): standardize executeJob calls with expect-exception helper
  engine/src/main/junit-shared/org/operaton/bpm/engine/impl/test/TestHelper.java
  engine/src/test/java/org/operaton/bpm/engine/impl/test/TestHelperTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/IncidentTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobEntityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/JobQueryTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/resources/HistoryByteArrayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/resources/RuntimeByteArrayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/FoxJobRetryCmdTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/async/JobRetryCmdWithDefaultPropertyTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/BoundaryTimerNonInterruptingEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/timer/StartTimerEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricJobLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceStateTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/jobexecutor/JobExecutorCmdExceptionTest.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/context/SetVariablesMigrationContextSwitchTest.java
  test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/bpmn/JobAssertHasExceptionMessageTest.java
Labels: qa, refactoring

#1297 chore(build): Update Maven plugins
  pom.xml
Labels: dependencies, build

#1298 feat(engine): extend queries with afterId filter
  engine/src/main/java/org/operaton/bpm/engine/history/HistoricVariableInstanceQuery.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricProcessInstanceQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricVariableInstanceQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricVariableInstanceQueryProperty.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ActivityInstanceImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/TransitionInstanceImpl.java
  engine/src/main/resources/org/operaton/bpm/engine/impl/mapping/entity/HistoricVariableInstance.xml
  engine/src/test/java/org/operaton/bpm/engine/test/api/queries/QueryByIdAfterTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/SubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricVariableInstanceTest.java
Labels: backport:c7, engine

#1311 chore(deps): Upgrade Spring to 6.2.11
  bom/internal-dependencies/pom.xml
  pom.xml
Labels: dependencies

#1337 fix(maven): upgrade unsecure URLs to HTTPS
  bom/operaton-bom/pom.xml
  bom/operaton-only-bom/pom.xml
  clients/java/pom.xml
Labels: refactoring

#1290 Enable users to start integration build scripts with mvnd
  .devenv/scripts/build/build-and-run-integration-tests.sh
  .devenv/scripts/build/build.sh
Labels: enhancement, build

#1367 refactor(tests): Replace try/catch with expected failure in test code
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/transactions/TransactionIntegrationTest.java
Labels: qa, refactoring

#1377 Updated jreleaser changelog for Quarkus upgrade.
  .github/jreleaser/changelog.tpl
Labels: documentation, dependencies

#1390 chore: Fix Sonar findings about naming convention
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/GroupRestService.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/authorization/AuthorizationResource.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/sub/identity/GroupResource.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/DbIdGenerator.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricExternalTaskLogManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/pvm/runtime/PvmExecutionImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/EnsureUtil.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/removaltime/HistoricRootProcessInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/mgmt/ManagementServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/multitenancy/query/history/MultiTenancyHistoricExternalTaskLogTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/cmmn/sentry/SentryVariableOnPartEntryCriteriaTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/calendar/DurationHelperTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/standalone/db/SchemaLogEnsureSqlScriptTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/util/ObjectProperty.java
  juel/src/main/java/org/operaton/bpm/impl/juel/Parser.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/impl/instance/ExtensionImpl.java
  model-api/bpmn-model/src/main/java/org/operaton/bpm/model/bpmn/instance/Extension.java
  model-api/cmmn-model/src/test/java/org/operaton/bpm/model/cmmn10/Cmmn10Test.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/beans/DemoDelegate.java
  test-utils/assert/core/src/test/java/org/operaton/bpm/engine/test/assertions/cmmn/CaseInstanceAssertTest.java
  webapps/assembly/src/test/java/org/operaton/bpm/webapp/impl/security/auth/AuthCacheTest.java
Labels: refactoring
