Repository operaton/operaton, pull requests merged in 2025-07, with the labels that each got.

#961 refactor: Fix @author redundant @camunda.com -> @operaton.com replacements
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Attribute.java
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Element.java
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/ModelConstants.java
  distro/wildfly/subsystem/src/main/java/org/operaton/bpm/container/impl/jboss/extension/Namespace.java
  distro/wildfly/subsystem/src/test/java/org/operaton/bpm/container/impl/jboss/test/JBossSubsystemXMLTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentResourceForIdCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetDeploymentResourcesCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskAttachmentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskAttachmentContentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetTaskCommentCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/PatchTaskVariablesCmd.java
  engine/src/main/java/org/operaton/bpm/engine/repository/Resource.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/jobexecutor/FailingJobBoundaryTimerWithDelegateVariablesTest.java
Labels: bug

#953 fix: Enable DB2 Tests on Wildfly and Tomcat
  database/pom.xml
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java
  qa/integration-tests-engine/src/test/resources-tomcat/arquillian.xml
  qa/tomcat-runtime/pom.xml
  qa/wildfly-runtime/pom.xml
  qa/wildfly-runtime/src/main/common/modules/com/ibm/db2/jcc/main/module.xml
  qa/wildfly-runtime/src/main/common/standalone/deployments/db2-ds.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
  test-utils/testcontainers/pom.xml
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonDb2ContainerProvider.java
  test-utils/testcontainers/src/main/resources/META-INF/services/org.testcontainers.containers.JdbcDatabaseContainerProvider
  test-utils/testcontainers/src/test/java/org/operaton/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
Labels: qa, database

#950 fix: Enable MySQL Tests on Wildfly and Tomcat
  database/pom.xml
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/util/ArquillianEventObserver.java
  qa/tomcat-runtime/pom.xml
  qa/wildfly-runtime/pom.xml
  qa/wildfly-runtime/src/main/common/modules/com/mysql/mysql-connector-j/main/module.xml
  qa/wildfly-runtime/src/main/common/standalone/deployments/mysql-ds.xml
  qa/wildfly-runtime/src/main/wildfly/standalone/configuration/standalone.xml
  test-utils/testcontainers/src/test/java/org/operaton/impl/test/utils/testcontainers/DatabaseContainerProviderTest.java
Labels: qa, database

#991 Fix HistoricDecisionInstanceStatisticsQuery should throws NullValueException
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricDecisionInstanceStatisticsQueryImpl.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoricDecisionInstanceStatisticsQueryTest.java
Labels: bug

#999 fix(test): Use the recommended connection parameters for MySQL
  test-utils/testcontainers/src/main/java/org/operaton/impl/test/utils/testcontainers/OperatonMySqlContainerProvider.java
Labels: database

#1004 refactor: use isEmpty() to check whether a StringBuilder is empty or not
  engine/src/main/java/org/operaton/bpm/engine/impl/application/ProcessApplicationManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/bpmn/parser/BpmnParse.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmmn/handler/ItemHandler.java
  qa/integration-tests-engine/src/test/java/org/operaton/bpm/integrationtest/functional/database/PurgeDatabaseTest.java
  webapps/assembly/src/main/java/org/operaton/bpm/webapp/impl/security/filter/Authorization.java
Labels: refactoring

#981 feat: add ADR template and README for architectural decisions
  .github/workflows/build.yml
  CONTRIBUTING.md
  NOTICE
  README.md
  docs/decisions/.markdownlint.yml
  docs/decisions/README.md
  docs/decisions/adr-template.md
Labels: documentation

#1019 Move CollectionUtil to commons/utils & add test #1007
  commons/utils/src/main/java/org/operaton/commons/utils/CollectionUtil.java
  commons/utils/src/test/java/org/operaton/commons/utils/CollectionUtilTest.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/batch/BatchQueryDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/externaltask/FetchExternalTasksDto.java
  engine-rest/engine-rest/src/main/java/org/operaton/bpm/engine/rest/dto/runtime/JobQueryDto.java
  engine-spring/src/test/java/org/operaton/bpm/engine/spring/test/taskassignment/CustomTaskAssignmentTest.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricExternalTaskLogQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/HistoricJobLogQueryImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/SetJobsRetriesByProcessBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractSetExternalTaskRetriesCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/AbstractUpdateProcessInstancesSuspendStateCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/GetActivityInstanceCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/SetJobsRetriesBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/CorrelateAllMessageBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/DeleteHistoricProcessInstancesBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/DeleteProcessInstanceBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/removaltime/SetRemovalTimeToHistoricDecisionInstancesCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/removaltime/SetRemovalTimeToHistoricProcessInstancesCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/cmd/batch/variables/SetVariablesToProcessInstancesBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/entitymanager/DbEntityManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/db/sql/BatchDbSqlSession.java
  engine/src/main/java/org/operaton/bpm/engine/impl/dmn/cmd/DeleteHistoricDecisionInstancesBatchCmd.java
  engine/src/main/java/org/operaton/bpm/engine/impl/externaltask/FetchAndLockBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/jobexecutor/JobAcquisitionContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/instance/parser/MigratingInstanceParseContext.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/validation/instance/VariableConflictActivityInstanceValidator.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/validation/instruction/SameBehaviorInstructionValidator.java
  engine/src/main/java/org/operaton/bpm/engine/impl/migration/validation/instruction/ValidatingMigrationInstructions.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/ExecutionEntity.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/HistoricProcessInstanceManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/persistence/entity/JobManager.java
  engine/src/main/java/org/operaton/bpm/engine/impl/repository/DeploymentBuilderImpl.java
  engine/src/main/java/org/operaton/bpm/engine/impl/task/TaskDefinition.java
  engine/src/main/java/org/operaton/bpm/engine/impl/util/CollectionUtil.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/form/FormServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/history/HistoryServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/api/runtime/RuntimeServiceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/callactivity/CallActivityTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/event/error/BoundaryErrorEventTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/ExclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/gateway/InclusiveGatewayTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/mail/EmailSendTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/mail/EmailServiceTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/multiinstance/MultiInstanceTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/scripttask/ScriptTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/sequenceflow/ConditionalSequenceFlowTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/sequenceflow/DefaultSequenceFlowTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/servicetask/JavaServiceTaskTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/bpmn/subprocess/SubProcessTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/CustomHistoryEventHandlerTest.java
  engine/src/test/java/org/operaton/bpm/engine/test/history/HistoricVariableInstanceTest.java
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/DeleteDeploymentCascadeTest.java
  qa/large-data-tests/src/test/java/org/operaton/bpm/qa/largedata/util/EngineDataGenerator.java
Labels: refactoring, migration
